### PR TITLE
fix: replace [kK]ey[cC]loac?k with [kK]eycloak

### LINKED ISSUE #518: Replace KeyCloak with Keycloak
There are 92 occurrences of the term "KeyCloak" in the repository. However, the correct spelling is "Keycloak" (source: https://www.keycloak.org/).

### PR DESCRIPTION
**Pull request by florianrusch-zf**
## Description

There are 92 occurrences of the term "KeyCloak" in the repository. However, the correct spelling is "Keycloak" (source: https://www.keycloak.org/).

Fixes #518 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

⚠️ I didn't tick the last checkbox because there are a lot of files that have no copyright and licence header at all. I believe this should be added in a separate PR rather than this one.

### CODE REVIEW

**Review by tomaszbarwicki — DISMISSED** [review]
LGTM

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by drcgjung — APPROVED** [review]
very neat initiative. You could, however, also replace occurences of "[kK]ey[cC]loack" in 6 files.

image

**Comment by florianrusch-zf** [comment]
> very neat initiative. You could, however, also replace occurences of "[kK]ey[cC]loack" in 6 files.


Good catch! I will do that 😉

**Comment by stephanbcbauer** [comment]
> > very neat initiative. You could, however, also replace occurences of "[kK]ey[cC]loack" in 6 files.
> 
> Good catch! I will do that 😉

Can you manage this before merging? ;)

**Comment by florianrusch** [comment]
I will fix the typos after my vacations ;-) Just let's keep this PR open until I fixed them as well.

**Comment by florianrusch-zf** [comment]
I have left the following as it is because these occurrences refer to a script in another repo which I don't want to touch at the moment:

- `docs-kit/kits/Data Chein Kit/page_software-operation-view.md:215`
- `docs-kits_versioned_docs/version-23.09/kits/Data Chain Kit/page_software-operation-view.md:207`
- `docs-kits_versioned_docs/version-23.12/kits/Data Chain Kit/page_software-operation-view.md:215`
- `docs-kits_versioned_docs/version-3.1.0/kits/Data Chain Kit/page_software-operation-view.md:207`

**Review by drcgjung — APPROVED** [review]
Perfect.

**Review by FaGru3n — DISMISSED** [review]
LGTM

**Comment by carslen** [comment]
Wanted to merge PR, but it has merge conflicts. Please resolve merge conflicts @florianrusch-zf

**Comment by stephanbcbauer** [comment]
@florianrusch, @carslen  I could take over this PR, if needed

**Comment by florianrusch-zf** [comment]
i have already merged the changes locally and will push them later 😉
________________________________

**Review by stephanbcbauer — APPROVED** [review]
Thank you very much @florianrusch for this effort

**Review by carslen — APPROVED** [review]

**Pull request merged**
