### PR TITLE
Connector: Upate to latest (2408) DataExchangeGovernance

### PR DESCRIPTION
**Pull request by matgnt**
Instead of use case specific legal documents / credentials, there is now a single consolidated document and consquently also a single Verifiable Credential. Policies need to be updated accordingly.

### CODE REVIEW

**Comment by arnoweiss** [comment]
Thanks for the contribution! Do you expect there to be more consumer/provider facing changes in R24-08?

**Comment by matgnt** [comment]
> Thanks for the contribution! Do you expect there to be more consumer/provider facing changes in R24-08?

From a Data Sovereignty perspective compared to 2405: No.
Only a few purposes that were not legally clarified are resolved now.
But the biggest change is the single Governance document instead of use case specific ones.

I also introduced a Changelog in the CX ODRL Profile repo:
https://github.com/catenax-eV/cx-odrl-profile/blob/main/CHANGELOG.md

**Comment by matgnt** [comment]
just also added an update to the Connector Kit changelog

**Comment by matgnt** [comment]
cc: @mhellmeier @markuskeidl

**Review by arnoweiss — APPROVED** [review]

**Review by mhellmeier — APPROVED** [review]

**Pull request merged**
