### PR TITLE
doc: set DT Kit to 1.0.0

### PR DESCRIPTION
**Pull request by arnoweiss**
## Description
This PR includes the last fixes after qg4-review. It bumps the version to 1.0.0, reflecting the conditional approval of release management.

### CODE REVIEW

**Comment by arnoweiss** [comment]
@LuisRickert - with the release, the kit should also be moved to the "versioned-docs" folder, right? Is there any documentation how to do this, especially since there's no versioned sidebar for R3.2 yet?

**Comment by LuisRickert** [comment]
> @LuisRickert - with the release, the kit should also be moved to the "versioned-docs" folder, right? Is there any documentation how to do this, especially since there's no versioned sidebar for R3.2 yet?

yes and no, with every Release the maintainer of the Tractus-X run a script that does this for you. You commit your changes to your fork and merge them via a pull request into the "docs" folder. The "versioned-docs" directory shall not be modified by others than the Tractus-X Maintainer.

**Comment by arnoweiss** [comment]
@SebastianBezold 
Please review if all considerations from QG4 review have been addressed. Thanks!

**Review by SebastianBezold — APPROVED** [review]

**Comment by SebastianBezold** [comment]
Changes look good to me. 👍 
The only thing that got my attention is the spaces in the KIT directory names. The link with html encoded spaces you had to use is hard to read and hard to maintain, ones things are moved. But this is something we should consider as issue and separate PR, since it would affect all KITs and already existing links

**Comment by arnoweiss** [comment]
Ready for merge

**Pull request merged**
