### PR TITLE
Update: Create Release 24.12

### PR DESCRIPTION
**Pull request by jSchuetz88**
This PR creates the latest Eclipse Tractus-X Release for R24.12. This includes:

- the creation of the new version R24.12
- the removal of the oldest version R24.05

IP-Ticket is created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17621

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
Please merge after IP issues was approved

**Comment by stephanbcbauer** [comment]
Please merge after https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1107 was merged

**Comment by jSchuetz88** [comment]
@matbmoser, Could you please check. It seems Trufflehog does not like the following line:

> jdbcUrl: jdbc:postgresql://agent-postgresql2:5432/consumer

It doesn't seem to be an issue for me?

**Comment by matbmoser** [comment]
This pr needs to be merged so we can stop having false positives:
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1094

**Comment by jSchuetz88** [comment]
> This pr needs to be merged so we can stop having false positives: #1094

done.

**Comment by stephanbcbauer** [comment]
@matbmoser issue was closed

**Review by matbmoser — APPROVED** [review]

**Pull request merged**
