### PR TITLE
(fix): Fix Typo 2023-09-08-release-23.09.md

### PR DESCRIPTION
**Pull request by aaniin**
## Description
Changed typo in 23.09 blog: exiting to exciting

## Pre-review checks
- [ yes ] dependencies are up to date
- [ yes ] Copyright and license header are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by carslen — CHANGES_REQUESTED** [review]
Please sign Eclipse Contributor Agreement (ECA). Only contributions from contributors with signed ECA will be accepted for merging PRs.

Details can be found here: [Eclipse-TractusX/DeveloperHub/FAQ](https://eclipse-tractusx.github.io/docs/dev_faq#the-eca-check-is-failing-while-merging-a-pr-what-to-do)

**Comment by maximilianong** [comment]
Any updates here? If not - I would takeover this small change and raise a new PR because @danielmiehle and me were posting this blog entry initially.

**Comment by carslen** [comment]
@maximilianong just do it, don't let us waste more time on this simple typo. :)

Closing this PR.

**Comment by carslen** [comment]
To track issue I've opened #423

**Pull request closed without merging**
