### PR TITLE
chore(ecopass-kit): added R24.08 changelog for the ecopass-kit

### PR DESCRIPTION
**Pull request by matbmoser**
## Description
We need to generate a proper changelog for this R24.08.

This is the changelog: 

### 24.08 Added

- Added Digital Product Pass Verification Section in adoption view
- Added Digital Product Pass Tutorial Section adoption view & software view
- Added Digital Product Passport as Enabler for Circular Economy Whitepaper reference

### 24.08 Updated

- Updated DPP model to version v5.0.0
- Updated BatteryPass to v6.0.0
- Updated TransmissionPass to v3.0.0
- Updated DPP Verification add-on in the software development view.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by matbmoser** [comment]
Ok the change logs are created and ready to be merged!

**Review by jSchuetz88 — APPROVED** [review]
Looks good to me.

**Review by saudkhan116 — APPROVED** [review]

**Review by danielmiehle — APPROVED** [review]
LGTM

**Comment by matbmoser** [comment]
Thx everyone!

**Pull request merged**
