### PR TITLE
OSim KIT 24.08

### PR DESCRIPTION
**Pull request by dominikoeh**
### Added

- Adoption View:
  - Added new Chapter Product documentation with a link to the document.

### Changed

- Adoption View:
  - Updated the aspect model references to the newest version.
- Development View:
  - Updated the API descriptions in accordance with the newest OSim standardization document CX-133

### Removed

- Adoption View:
  - References to the obsolete OSim Standards.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by danielmiehle — DISMISSED** [review]
LGTM - thanks for the new contributions and adaptions.

**Review by jSchuetz88 — APPROVED** [review]
Hi @dominikoeh,

looks good to me, but please consider to update the APIs, as the openAPI plugin will be discontinued and the API and the respective MDX-files needs to be removed, please see the following guidance:  https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/970

**Comment by maximilianong** [comment]
Hi @dominikoeh can you please provide the API file as an .yaml

**Comment by dominikoeh** [comment]
> Hi @dominikoeh can you please provide the API file as an .yaml

@maximilianong API file as been added as `.yaml`

**Review by maximilianong — APPROVED** [review]

**Comment by stephanbcbauer** [comment]
Discussed with @jSchuetz88 can be merged

**Pull request merged**
