### PR TITLE
chor: remove license file

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

Remove license file from the root

## Issue

https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles/issues/16

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by manojava-gk** [comment]
*  Add a new file LICENSE_non-code in your repository root with the contents of the CC-BY-4.0 license - **already available**
*  Remove the /LICENSES directory in case you previously stored the CC-BY-4.0 license there. Make sure there is no other CC-BY-4.0 License left, other than on root as LICENSE_non-code - **removed**
*  Add the "Project Licenses" and "Terms of Use" sections to your CONTRIBUTING.md file. See Update legal docs (TRG7) sig-infra#476 for an example - **already added**
*  Adapt "Declared Project License" section in NOTICE.md.  - **already present**
*  Please verify, your CONTRIBUTION.md does not have encoding issues. - **not sure what is encoding issue? I do not see any issue in the editor**

**Comment by danielmiehle** [comment]
Hi @manojava-gk thanks for preparing the PR, but this is the wrong repo. Please create the PR for the following repo:

https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles

**Comment by manojava-gk** [comment]
My bad. Got it. Will create it from another repo.
Btw, deleting the license file is also part of the task. I hope this PR is relevant to that point. Let me know otherwise, will close this PR @danielmiehle

**Review by arnoweiss — CHANGES_REQUESTED** [review]
I'm pretty sure this is a bad idea.

The repository is consists of code and non-code components. The licence file that this PR would remove is still relevant for the logical components of this repository. Closing this PR within a week unless someone disagrees with this position.

**Pull request closed without merging**
