### PR TITLE
Update page_changelog.mdx

### PR DESCRIPTION
**Pull request by mkanal**
## Description
- Correct link leading to 404 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by ds-mwesener — DISMISSED** [review]
LGTM

**Comment by stephanbcbauer** [comment]
@ds-mwesener please review again, I updated the DEPENDENCIES file

**Review by stephanbcbauer — APPROVED** [review]
LGTM

**Comment by stephanbcbauer** [comment]
@eclipse-tractusx/automotive-tractusx-committers we would need a second review here. Thx

**Pull request merged**
