### PR TITLE
doc(tutorials): Update prerequisites - make it more readable

### PR DESCRIPTION
**Pull request by JohannesARENA2036**
## Description

Minor changes - the commands are now displayed in separate code blocks -> easier to copy and execute step by step.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@JohannesARENA2036 i am a little bit confused. Didn't we already merge these changes with your pach4? Can we please sync again? Thx

**Comment by stephanbcbauer** [comment]
@JohannesARENA2036 i merged main into your branch… what is left right now in the PR are the separate code snippets… it makes it easier to copy and execute them. THX

**Comment by FaGru3n** [comment]
Only thing is left is dependencies check. The rest looks good to me

> - [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by florianrusch-zf — APPROVED** [review]

**Comment by stephanbcbauer** [comment]
> Only thing is left is dependencies check. The rest looks good to me
> 
> > * [x]  DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.

done
image

**Pull request merged**
