### PR TITLE
new(Carousel): role based entry and community contribute

### PR DESCRIPTION
**Pull request by manojava-gk**
Carousel component for role based entry - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/348
Grey carousel component for navigation - https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/350

### CODE REVIEW

**Comment by carslen** [comment]
@maximilianong @danielmiehle 
Please review this PR.

**Comment by carslen** [comment]
Who feels responsible for the website? @danielmiehle @maximilianong @Siegfriedk 

When reviewing the changes, consider to execute the docusaurus dev server locally to check it the website will be functional.

**Comment by Siegfriedk** [comment]
> Who feels responsible for the website? @danielmiehle @maximilianong @Siegfriedk
> 
> When reviewing the changes, consider to execute the docusaurus dev server locally to check it the website will be functional.

I believe that @manojava-gk is commisioined by @maximilianong

**Comment by maximilianong** [comment]
Sorry for the late response @carslen 

The module itself is right - the content not.
We will finalize this next week.

**Pull request merged**
