### PR TITLE
docs: prepare release for Industry Core and Traceability KIT (24.08.)

### PR DESCRIPTION
**Pull request by mhellmeier**
## Description
This PR updates the changelog for the Traceability KIT and Industry Core KIT and relates it to the upcoming release 24.08.

### Related Issues

- FIxes https://github.com/eclipse-tractusx/sig-release/issues/573
- FIxes https://github.com/eclipse-tractusx/sig-release/issues/574

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by jSchuetz88 — COMMENTED** [review]
Hi @mhellmeier, thank you for the contribution.

I have a few questions:
 - Is there a corresponding Release Check Ticket in sig-release? I can't find one for the Traceability nor for the Industry Core Kit. 
 - How does this PR relate to 
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/936

**Comment by mhellmeier** [comment]
Regarding your questions:
 
> * Is there a corresponding Release Check Ticket in sig-release? I can't find one for the Traceability nor for the Industry Core Kit.

Yes, the issue in sig-release is already linked in the description of this PR. Please have a look at it above.

> * How does this PR relate to
>   [[Traceability KIT 24.08] Updated Software Development View #936](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/936)

Your linked pull request is only a small enhancement from one team member. This pull request (#980) is the main one.

**Review by eckardg — APPROVED** [review]

**Review by danielmiehle — DISMISSED** [review]
LGTM

**Review by jSchuetz88 — APPROVED** [review]

**Comment by mhellmeier** [comment]
We expect to wait for #936 before we merge this PR.

**Review by jSchuetz88 — APPROVED** [review]
Thank you for including the suggestions and for cleaning up the previous PR.

**Review by danielmiehle — DISMISSED** [review]

**Comment by mhellmeier** [comment]
I corrected some broken links.

Fixes #998

**Review by arnoweiss — APPROVED** [review]

**Review by arnoweiss — APPROVED** [review]

**Review by danielmiehle — APPROVED** [review]

**Pull request merged**
