### PR TITLE
[Business Partner KIT]: removed open api plugin usage

### LINKED ISSUE #971: [Business Partner KIT] Remove API Plug-In DRAFT
Please refer to https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/970 to see tasks and acceptance criteria.

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description

With this pull request, removed open api plugin usage for business patner kit and also removed unnecessary `.mdx` files. We have added hyperlink of swagger documentation for each service from bpdm in business partner kit's development view which make kit more readable.

Fix #971 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by SujitMBRDI** [comment]
Hi @jSchuetz88 @danielmiehle , could you please check pull request as waiting from long time.

**Review by jSchuetz88 — CHANGES_REQUESTED** [review]
Hi @SujitMBRDI,

thank you for removing the API. I actually like the idea, to update the references to the SwaggerHub instead of removing them completely. Unfortunately, the links to SwaggerHub don't work right now, but that should be automatically fixed, after the merge and automated scan of the openAPIs.

Only one change request (@danielmiehle please correct me here if I'm wrong): But the references also need to be removed from previous versions and not only for the "next" release. Otherwise we won't be able to update Docusaurus.

**Comment by SujitMBRDI** [comment]
> Hi @SujitMBRDI,
> 
> thank you for removing the API. I actually like the idea, to update the references to the SwaggerHub UI instead of removing them completely. Unfortunately, the links to SwaggerHub don't work right now, but that should be automatically fixed, after the merge and automated scan of the openAPIs.
> 
> Only one change request (@danielmiehle please correct me here if I'm wrong): But the references also need to be removed from previous versions and not only for the "next" release. Otherwise we won't be able to get rid of the plugin.

Hi @jSchuetz88,

Thank you for reviewing the changes. Good to hear that you like the idea where we are linking api-hub swagger documentation for development view. Also you are right, the links will work after merge and once automated scan for OpenApi finish. I have provided link based on expected result of auto scan(it is high guess from our side).
So, there are high chances that I need to put another pull request if links appear differently on api-hub.
The reason why, i want this pull request to reviewed and merge first. In my second pull request(which i shall raise after scan results) i shall update links for swagger documentation if they are wrong for next version and will also make changes for previous release versions. I hope @danielmiehle, @jSchuetz88 and @maximilianong  will agree to this approach.

**Comment by stephanbcbauer** [comment]
[IP Ticket](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16323) created

**Comment by stephanbcbauer** [comment]
@jSchuetz88 IP Ticket is still under review

**Comment by SujitMBRDI** [comment]
Hi @jSchuetz88, @stephanbcbauer I can see the IP ticket is approved as well.

**Pull request merged**
