### PR TITLE
Demand and Capacity Management KIT 24.12

### PR DESCRIPTION
**Pull request by ClosedSourcerer**
## Description
This PR introduces the Next Version of the Demand and Capacity Management KIT

### Addressed Issues

https://github.com/eclipse-tractusx/sig-release/issues/838
https://github.com/eclipse-tractusx/sig-release/issues/799
https://github.com/eclipse-tractusx/sig-release/issues/780
https://github.com/eclipse-tractusx/sig-release/issues/773
https://github.com/eclipse-tractusx/sig-release/issues/772
https://github.com/eclipse-tractusx/sig-release/issues/771
https://github.com/eclipse-tractusx/sig-release/issues/770
https://github.com/eclipse-tractusx/sig-release/issues/769
https://github.com/eclipse-tractusx/sig-release/issues/766

### Added

- Added E2E Tests to [Development View](./development-view/overview.md)
- Added Glossary to [Adoption View](./adoption-view/overview.md)
- Added Delta Production to [Adoption View](./adoption-view/overview.md)
- Added Demand Volatility to [Adoption View](./adoption-view/overview.md)
- Added Load Factors to [Adoption View](./adoption-view/overview.md)
- Added Nesting to [Adoption View](./adoption-view/overview.md)
  
### Changed

- Updated [Core Business Process](./adoption-view/use-case/business-process.md) with assorted examples of capacity groups and material demands
- Updated [Onboarding](./adoption-view/onboarding.md) to include an onboarding journey

### Bug Fixes

- Removed Catena-X NG reference
- Unified License Notice for DCM KIT
- Renamed DCM KIT in the sidebar and header into Demand and Capacity Management KIT in order to be consistent with the other KITs 

## Pre-review checks

Docusaurus builds locally all touched pages run fine locally

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [X] [IP-Issue created](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16849)

### CODE REVIEW

**Comment by ClosedSourcerer** [comment]
@pdequick 
@lanfrans 
@Frank-Globisch 

Please, as previously mentioned, take care of linking your github and eclipse accounts as well as signing the ECA Eclipse contributors agreement.

**Comment by ClosedSourcerer** [comment]
I will take care of the linting Issues

**Comment by ClosedSourcerer** [comment]
@jSchuetz88 
@stephanbcbauer 

I am quite convinced, that the GitRunner is broken: 
image

The referenced Image file does exist, is a correctly formated .svg and can be previewed / build locally.

Maybe some stupid character limit for the total file length, as we referenced path is >127 chars?

**Comment by stephanbcbauer** [comment]
> @jSchuetz88 @stephanbcbauer
> 
> I am quite convinced, that the GitRunner is broken: image
> 
> The referenced Image file does exist, is a correctly formated .svg and can be previewed / build locally.
> 
> Maybe some stupid character limit for the total file length, as we referenced path is >127 chars?

@ClosedSourcerer I think the naming is not correct. In the file its `Legend` and in the markdown you are referencing `legend`

```
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/d027ce44dc5391e98ff0a08380500a9dcaa00f9f/docs-kits/kits/Demand%20and%20Capacity%20Management%20Kit/adoption-view/use-case/resources/business-process_DeltaProduction_functional_Legend.svg
```

**Comment by stephanbcbauer** [comment]
But I think we have some bigger issues ;) Markdown linting can be solved ⇾ easy, but there are some contributors who didn't sign the ECA? That's a problem.

And for this PR we need IP Ticket because of the bug number of changes. Can you change here somehow the working model?

**Comment by ClosedSourcerer** [comment]
> But I think we have some bigger issues ;) Markdown linting can be solved ⇾ easy, but there are some contributors who didn't sign the ECA? That's a problem.
> 
> And for this PR we need IP Ticket because of the huge number of changes. Can you change here somehow the working model? No committer would be able to review this PR

@MWADCM 
@LukasSchmetz 

1. As expert group lead the working model is your issue.
2. Please also initiate the IP Ticket with our designated commiter.
3. @eckardg Also contacted me regarding @lanfrans requirement for the Eclipse account and ECA. Please take care of this as well

**Comment by stephanbcbauer** [comment]
> > But I think we have some bigger issues ;) Markdown linting can be solved ⇾ easy, but there are some contributors who didn't sign the ECA? That's a problem.
> > And for this PR we need IP Ticket because of the huge number of changes. Can you change here somehow the working model? No committer would be able to review this PR
> 
> @MWADCM @LukasSchmetz
> 
> 1. As expert group lead the working model is your issue.
> 2. Please also initiate the IP Ticket with our designated commiter.
> 3. @eckardg Also contacted me regarding @lanfrans requirement for the Eclipse account and ECA. Please take care of this as well

Meanwhile i created the [IP Issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16849)

**Comment by ClosedSourcerer** [comment]
@jSchuetz88 
An exact date (yyyy-mm-dd) for the release of the 24.12 KIT is required.

`docs-kits/next/kits/Demand and Capacity Management Kit/changelog` needs to be updated accordingly

**Review by MWADCM — APPROVED** [review]

**Review by jschu1 — APPROVED** [review]
Great improvement

**Comment by stephanbcbauer** [comment]
> > > But I think we have some bigger issues ;) Markdown linting can be solved ⇾ easy, but there are some contributors who didn't sign the ECA? That's a problem.
> > > And for this PR we need IP Ticket because of the huge number of changes. Can you change here somehow the working model? No committer would be able to review this PR
> > 
> > 
> > @MWADCM @LukasSchmetz
> > 
> > 1. As expert group lead the working model is your issue.
> > 2. Please also initiate the IP Ticket with our designated commiter.
> > 3. @eckardg Also contacted me regarding @lanfrans requirement for the Eclipse account and ECA. Please take care of this as well
> 
> Meanwhile i created the [IP Issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16849)

@jSchuetz88 , @ClosedSourcerer Wow this was fast -> IP Tickets was approved

image

**Review by kenobi79 — APPROVED** [review]
LGTM

**Review by reginePrivat — APPROVED** [review]

**Comment by jSchuetz88** [comment]
> @jSchuetz88
> 
> * When the KIT gets released with 24.12 should the changelog.md of tractus-X (https://eclipse-tractusx.github.io/CHANGELOG/) get changed as well in order to reflect the move from  `/DCM-KIT/` to `/Demand and Capacity Management KIT/`

@ClosedSourcerer Sorry for the late reply.

**Initial PR at latest**: 15.11
**Merged at latest**: 29.November
**Formal publication (creation of the new Version / Release)**: 2. December

**Review by LukasSchmetz — APPROVED** [review]
Corrections implemented as discussed with @ClosedSourcerer . LGTM

**Comment by stephanbcbauer** [comment]
> The Eclipse Dash is erroneous. Afaik this is known to @stephanbcbauer
> 
> From a business perspective: We did nit add any code, therefore any code dependencies to the KIT.
> 
> @danielmiehle If I remember correctly you volunteered to act as committer for this PR.
> 
> * How do we proceed now?

@ClosedSourcerer in this case it's not the broken checker. There is really an issue. "Your" DEPENDECIES file is not up-to-date. There are new states "on the server" which are right now not in your DEPENDENCIES file. This is not done automatically.

left your file, right the new status of the lib
image


There are two options:
1. maybe someone already updated the DEPENDENCIES file on main, and you can just merge it
2. you have to update the file locally on your own and push it to your branch

**Comment by stephanbcbauer** [comment]
> > The Eclipse Dash is erroneous. Afaik this is known to @stephanbcbauer
> > From a business perspective: We did nit add any code, therefore any code dependencies to the KIT.
> > @danielmiehle If I remember correctly you volunteered to act as committer for this PR.
> > 
> > * How do we proceed now?
> 
> @ClosedSourcerer in this case it's not the broken checker. There is really an issue. "Your" DEPENDECIES file is not up-to-date. There are new states "on the server" which are right now not in your DEPENDENCIES file. This is not done automatically.
> 
> left your file, right the new status of the lib image
> 
> There are two options:
> 
> 1. maybe someone already updated the DEPENDENCIES file on main, and you can just merge it
> 2. you have to update the file locally on your own and push it to your branch

Additional information to update the DEPENDENCIES file ... here the command, needs to be executed in root folder

```
java -jar org.eclipse.dash.licenses-1.1.0.jar package-lock.json -project automotive.tractusx -summary ./DEPENDENCIES
```

https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool

**Comment by ClosedSourcerer** [comment]
@stephanbcbauer Thank you, I already had dependencies mentally taken care off and totally forgot that between the DB being down and dash working beforehand that I might just need to merge the upstream back into downstream to get this fixed.

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer Thank you, I already had dependencies mentally taken care off and totally forgot that between the DB being down and dash working beforehand that I might just need to merge the upstream back into downstream to get this fixed.

i think merging helped :)

**Review by danielmiehle — APPROVED** [review]
lgtm

**Pull request merged**
