### PR TITLE
chore(markdown linter): fix markdownlinter issues

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

Since the markdown linter was also activated for docs-kits folder structure, we receive many new issues. A lot of them couls be fixed via this PR.

To fix them, the following command was executed

```shell
markdownlint-cli2 --fix "**/*.md" "#node_modules"
```
I am not sure if such a PR makes sense.

**Still a lot of issues needs to be fixed manual.**

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM if some more Markdown would be lower

**Comment by stephanbcbauer** [comment]
Please don't review this DRAFT PR → I think the idea was good, but there are too many changes. And also, the automatic fixes are not always good. :)

**Will close this PR**

**Comment by mhellmeier** [comment]
Every team publishing a KIT is responsible for submitting it in the proper format. I created different Issues for every KIT.

**Comment by stephanbcbauer** [comment]
as discussed, will be closed, since there are too many changes

**Comment by danielmiehle** [comment]
Thanks @mhellmeier for breaking down the issues.

**Pull request closed without merging**
