### PR TITLE
[Business Partner KIT] Release 24.08

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description

In this pull request, we have updated changes in business partner kit related to release 24.08.
- updated api endpoint details for bpdm services like gate, pool and orchestrator 
- removed documentation related to bpdm bridge dummy service 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by jSchuetz88** [comment]
Thank you for your contribution. 
As the change comprises more than 1000 lines, has an IP check already been triggered?
(TRG 7.03: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03/)

**Comment by SujitMBRDI** [comment]
> Thank you for your contribution. As the change comprises more than 1000 lines, has an IP check already been triggered? (TRG 7.03: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03/)
> 
> *Note: There is a chance, that the IP check won't be required. The openAPI plugin will be discontinued and the API and the respective MDX-files needs to be removed, please see the following guidance: #970
> 
> After the removal of the APIs maybe you won't have more than 1000 lines anymore.
> 
> @SujitMBRDI

@jSchuetz88,
Thanks for reviewing pull request.
Being committer, I think i can make the changes without creating IP check which I am quite use to do for this repo during multiple releases in past. 
(Ref TRG 7.03: [https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03/#contributions-by-a-tractus-x-committer)](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03/#contributions-by-a-tractus-x-committer)

Yeah, you rightly said after successful migration to API hub, we won't have more that 1000 lines anymore.
In past, I already tried SwaggerHub movement and their limitations are also well known for me. 
But are we planning to finish #970 in 24.08?

**Review by maximilianong — APPROVED** [review]

**Comment by jSchuetz88** [comment]
@SujitMBRDI 
> Being committer, I think i can make the changes without creating IP check which I am quite use to do for this repo during multiple releases in past.

My bad, you are right.

> But are we planning to finish https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/970 in 24.08?

Yes, we prepare to update docusaurus, which is currently blocked by the API plugin.

**Review by nicoprow — COMMENTED** [review]
The changes made here are all good.

However, since this pull request should reflect all updates for 24.08 I propose additional changes in the Operators View to remove outdated or confusing information. I created an issue for that here #990 

Question is just if we want to address these issues in this pull request or create a new one @SujitMBRDI

**Comment by SujitMBRDI** [comment]
> Question is just if we want to address these issues in this pull request or create a new one @SujitMBRDI
We can adapt operation view in same pull request.

**Comment by SujitMBRDI** [comment]
> > Question is just if we want to address these issues in this pull request or create a new one @SujitMBRDI
> 
> We can adapt operation view in same pull request.

@nicoprow  I have adapted changes for operation view mentioned in #990. Now, recent commit streamlines both BPDM repository information and information on present Business Partner KITs.

**Review by nicoprow — APPROVED** [review]
I think the Operation View had still some good parts we can overtake. But the content looks  good now and is up-to-date

**Review by maximilianong — APPROVED** [review]

**Review by Unsharm — APPROVED** [review]

**Pull request merged**
