### PR TITLE
fix: re-add CHANGELOG.md

### PR DESCRIPTION
**Pull request by SebastianBezold**
## Description

I accidentally deleted the `CHANGELOG` page in #840 and this PR is adding it again.
Before, I was under the impression, that the remote-content-plugin configured in [docusaurus.config.js](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/docusaurus.config.js#L152-L161) would add that at build time. 

This PR is just for quick fixing. Afterwards, I think we should find a straight forward approach for maintaining the duplicated `CHANGELOG.md` on the website.

Thanks @evegufy for finding the missing `CHANGELOG` and [letting me know](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/840#issuecomment-2056394671) 😁 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by evegufy — CHANGES_REQUESTED** [review]
website build check fails, can you please confirm that that's not related to this change?

**Comment by SebastianBezold** [comment]
> website build check fails, can you please confirm that that's not related to this change?

It actually is related it seems. I was using the latest `CHANGELOG.md` from tractus-x-release repo, but this does not seem to be "website ready".

I'll have to check the differences tomorrow. 
This to me even more shows, that it is unsustainable to duplicate the CHANGELOG. Maybe we should go for just linking

**Comment by SebastianBezold** [comment]
Hi @evegufy, 

I now used the `CHANGELOG.md` version from our history, so it includes the build fixes. 
I also opened a discussion to clarify, how we want to handle/represent the CHANGELOG on our website in general

Discussion: #844 

FYI: @Siegfriedk @stephanbcbauer @danielmiehle @maximilianong @FaGru3n

**Review by evegufy — APPROVED** [review]

**Review by FaGru3n — APPROVED** [review]

**Pull request merged**
