### PR TITLE
Simplify copy and pasting commands.

### PR DESCRIPTION
**Pull request by obermeier**
## Description
Removing the whitespace after the backslash allows the user to copy and paste the command to the console without the further modifications.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@obermeier thanks for solving this. Are there more of theses "issues" or is it only this particular one? i am just asking, cause we received some feedback on at the tractus-x community days, about more issues like this.

**Comment by obermeier** [comment]
> @obermeier thanks for solving this. Are there more of theses "issues" or is it only this particular one? i am just asking, cause we received some feedback on at the tractus-x community days, about more issues like this.

Thanks for the hint, @stephanbcbauer. I rechecked the repo with a simple regex and found this 'issue' only once.

**Comment by stephanbcbauer** [comment]
Since two reviews are needed, i also added @florianrusch-zf because he was involved in the Tractus-X community days and knows this issue :)

**Review by stephanbcbauer — APPROVED** [review]
LGTM ... important fix, cause otherwise the command wouldnt work.

**Comment by stephanbcbauer** [comment]
@florianrusch-zf could you also have a look, please? After this I am able to merge ;) Thx

**Review by carslen — APPROVED** [review]
LGTM

**Pull request merged**
