### PR TITLE
doc(open meetings): add new open meeting for trace-x

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This Prs add a new open meeting for trace-x to our [open meeting](https://eclipse-tractusx.github.io/community/open-meetings) page => There will be a new entry, which looks like:

image

Additional there will be a downloadable ics file which looks like after import:

image

_Unfortunately, we lose the formatting in the file_

Since we want to provide regular meetings and one-time meetings ... this PR also add the headlines for these categories.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@mkanal , @jzbmw please content review, @SebastianBezold  please general review. THX

**Comment by jzbmw** [comment]
@stephanbcbauer  is it possible to also already add links to the repo on toplevel of the meeting news?

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer is it possible to also already to have to info from the mail also available on toplevel of the meeting news? so that it is also possible to have the info without needing to download the ics files?

Also thought about it. Tried it, the formatting in the description didn't work for the first shot. I will add an issue for this.

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer bitte die <> bei dem Discussions Link entfernen.

done 
image

**Review by SebastianBezold — APPROVED** [review]
👍

**Review by mkanal — APPROVED** [review]

**Review by mkanal — APPROVED** [review]
LGFM

**Pull request merged**
