### PR TITLE
doc(open meetings): add new meeting structure for release 24.12

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR adds the new meetings for the Release Planning 24.12 to our open meeting page. After this PR is merged ... another PR will be created which includes the news blog section.

image

image

image

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by jSchuetz88 — APPROVED** [review]
All meeting information such as titles, schedules and calendar files (.ics) and links checked for functionality and consistency. Looks good.

**Review by HFocken — COMMENTED** [review]
Dates, content and language are fine - I would suggest one small change for the Refinement Phase to clarify that this is not an actual meeting but a calendar blocker for organizational purposes.

Suggested phrasing: "please be aware that the Refinement Phase is to keep you aware of the overall timeline during the Release Process and does not constitute an actual meeting. It serves informational purposes only."

**Comment by stephanbcbauer** [comment]
> please be aware that the Refinement Phase is to keep you aware of the overall timeline during the Release Process and does not constitute an actual meeting. It serves informational purposes only.

@HFocken => does this make sense for you 

```
Please be aware that the Refinement Phase is to keep you aware of the overall timeline during the Release Process and does not constitute an actual meeting. It serves informational purposes only. During this time, the necessary people/groups can come together and work on the future features. Feature authors take care of organising appointments and communicating with the relevant contacts themselves. The Teams Session link can be used. Be aware: The link and the shared content is available to everyone.
```

**Comment by stephanbcbauer** [comment]
Had to create a new PR #849

**Pull request closed without merging**
