### PR TITLE
fix(connector kit): fix markdown linter errors for connector kit

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

Some links (references in the documentation) are broken, and this PR fixes them. The errors were mentioned in #639 
This PR fixes the errors related to the tags @stephanbcbauer and @stefan-ettl 

The issue #639 cannot be closed by this PR because there are more errors from other kits.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by maximilianong — APPROVED** [review]

**Comment by maximilianong** [comment]
Thanks @stephanbcbauer for providing this quick fix.

**Comment by stephanbcbauer** [comment]
> Thanks @stephanbcbauer for providing this quick fix.



> Thanks @stephanbcbauer for providing this quick fix.

@maximilianong the strange thing … i think I am not done yet. At least for me, not all warnings are displayed. Whenever i fix some, others are displayed. So i think i need a little bit more time :) Will convert the PR after i am ready.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by maximilianong — APPROVED** [review]
👍

**Pull request merged**
