### PR TITLE
BPDM adoption view updated

### PR DESCRIPTION
**Pull request by maximilianong**
Just updated the adoption view of the business partner kit.

### CODE REVIEW

**Comment by FaGru3n** [comment]
Hi @maximilianong, 

seems the failed check is referencing your aggreement to our ECA within Eclipse Foundation. 
'https://accounts.eclipse.org/user/YOURUSERNUMBER/eca/3.1.0'

.. can also found under your Elclipse Foundation Profile.
my view
image

**Comment by maximilianong** [comment]
I don´t understand it - because I have checked ECA if I look into it:
Bildschirm­foto 2023-02-23 um 11 28 20

**Comment by maximilianong** [comment]
But I also see this .. with a ".net" address that I'm not aware of. I have the same @mercedes-benz.com mail in Github and Eclipse.

image001

**Comment by SebastianBezold** [comment]
Hi @maximilianong,
The commit, that you want to contribute is actually done with .net email: 'maxiong@capelhq78422214.destr.mc.corpintra.net' You can reference multiple email addresses in your GitHub account. The one you did the commit with, has to match the one you created your EF account with.
To change the email address you are committing with you can use the following command:
`git config --global user.email <your-email-address` If this setting only has to be changed for this specific repo, omit the `--global`. See also: [git handbook](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup).

To fix your current contribution either re-do it with the proper mail config, or `--amend` the commit

**Comment by SebastianBezold** [comment]
Looking at the .mdx file: I cannot access any of the linked .pdf files. Is this intended to be accessible at a later point, or are these broken links @maximilianong ?

**Pull request closed without merging**
