### PR TITLE
Add/feature multi-instance & versioning

### PR DESCRIPTION
**Pull request by santiagoejm**
This PR includes the discussed multi-instance & versioning features.

It can be divided in 3 major stages:

- Creation of multiple `docs-instances`:
    - default: `./docs` --> dedicated to the Developer Hub content (non versioned)
    - `./docs-kits` --> dedicated to all content related to `KITs` (versioned)
    - `./docs-products` --> dedicated to the content related to `products` (created for future development, can be versioned or non versioned. Currently is not been displayed in the `Navbar`)

- Regeneration of all endpoints created with the `docusaurus-openapi-docs` plugin, this step is required because the past content was generated in a different context (`./docs` instance), now the context change to `./docs-kits` instance.

- Creation of `version: 3.1.0`, that only refers to the content of the `docs-kits` instance

Other stages of this PR include updates to the `Navbar Items` routes, `React components` routes (both of them to navigate to correct documentation in the ./docs-kits folder) and implementation of the `docsVersionDropdown` item that has been `swizzled` to create the conditional rendering behaviour, resulting in the following UI only when the user is viewing the `docs-kits` content:

Screenshot 2023-05-31 at 12 24 58

@danielmiehle @Siegfriedk @maximilianong, please review it and give me your thoughts. Cheers!

### CODE REVIEW

**Comment by Siegfriedk** [comment]
Havent' read through it yet but i do like the new version much better

**Comment by Siegfriedk** [comment]
@santiagoejm can you check and fix the conflict asap? I would try to merge this pr to avoid merge conflicts in the future as it moves quite a lot of stuff around

**Comment by santiagoejm** [comment]
@Siegfriedk today I am back from vacations and just now I'm seeing your request, I haven't got an update yet about what was decided/news last week but I guess your request is still on. Before I solve the conflict, can you confirm that please?

PS @danielmiehle @maximilianong  in case you check it first.

**Comment by Siegfriedk** [comment]
@santiagoejm unclear tbh. I think its good enough to merge it and rework it later but i don't mind if you have to do more integration work if we decide this later, but i do will add content then.

Having this PR open for too long is risky IF the transofrmation you did is a lot of effort

**Comment by santiagoejm** [comment]
@Siegfriedk do you have any news about it?

**Comment by santiagoejm** [comment]
@Siegfriedk yes I talked to Max because Daniel is on vacation, I actually assumed that you wanted to give it a thought because you and/or the Developer Hub team were not sure about it. I just got a meeting with Max, he mentioned that he talked with you recently but this topic was not touched. I know Max approves it but should we schedule a meeting?

**Comment by Siegfriedk** [comment]
I'm all for merging it but we can also wait for Danile if you prefer

**Comment by santiagoejm** [comment]
Alright, I am also all up for it. Let me double check with Max about Daniel's views to reassure and not let room for misunderstandings. I'll come back to you, thanks!

**Comment by santiagoejm** [comment]
@Siegfriedk the conflicts are solved now, Max confirmed the merge as well. Whenever you have the time please merge it. Cheers!

**Pull request merged**
