### PR TITLE
fix: remove upcoming kits  add data governance kit

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

remove upcoming kits from next and 24.05.
add data governance kit in the nav bar

#921 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by arnoweiss — APPROVED** [review]

**Review by jSchuetz88 — CHANGES_REQUESTED** [review]
Hi @manojava-gk,
thank you for addressing the issue and for your contribution. However, I have one minor change request: You removed the "upcoming kits" from the sidebar, but not from the drop-down menu.

**Comment by manojava-gk** [comment]
> Hi @manojava-gk, thank you for addressing the issue and for your contribution. However, I have one minor change request: You removed the "upcoming kits" from the sidebar, but not from the drop-down menu in the navigation on the top in _docusaurus.config.js_.

Its done

**Review by danielmiehle — APPROVED** [review]
Thanks for fix!

**Review by jSchuetz88 — APPROVED** [review]
Thank you, LGTM.

**Review by arnoweiss — APPROVED** [review]

**Comment by jSchuetz88** [comment]
@arnoweiss @danielmiehle @maximilianong @stephanbcbauer
Could someone merge this PR? I would prefer to merge this PR before creating a new release.

**Pull request merged**
