### PR TITLE
Upgraded some dependencies

### PR DESCRIPTION
**Pull request by the-tatanka**
run shrinkwrap, updated webpack & eta & async

### CODE REVIEW

**Comment by the-tatanka** [comment]
15 high severity vulnerabilities left - no fix available, it seems.
eca does not work - yes it is checked in my eclipse acc.

**Comment by FaGru3n** [comment]
Hi @the-tatanka seems ECA is missing for your account.
you will find this under your EF profile
image

**Comment by the-tatanka** [comment]
image

**Comment by FaGru3n** [comment]
hi @the-tatanka 

i think you used a different mailadress for your github account and your EF (Eclipse Foundation) account, should the same i guess.

**Pull request closed without merging**
