### PR TITLE
DCM-KIT for Release 24.08

### PR DESCRIPTION
**Pull request by ClosedSourcerer**
## Description

This PR contains the DCM-Kit for release 24.08.
Only the DCM-KIT (and links to the DCM KIT) are affected by this PR
image
*Figure: Changed Files*

The following issues are addressed.

https://github.com/eclipse-tractusx/sig-release/issues/587
https://github.com/eclipse-tractusx/sig-release/issues/585
https://github.com/eclipse-tractusx/sig-release/issues/608

https://github.com/catenax-eV/cx-ex-dcm/issues/14
https://github.com/catenax-eV/cx-ex-dcm/issues/21
https://github.com/catenax-eV/cx-ex-dcm/issues/12
https://github.com/catenax-eV/cx-ex-dcm/issues/7
https://github.com/catenax-eV/cx-ex-dcm/issues/10

Some highlites:
- Added missing license information (TRG.7.08)
- Introduced Swagger API documentation
- Introduced Q&A
- Refined On-Boarding
- Restructured Kit
- Added sections for Standard Add Ons

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ClosedSourcerer** [comment]
Regarding ECA:

image
That is my local account. 
After a GIT update i needed to reset my config, hence one or two commits were using my local account.

**Review by jschu1 — APPROVED** [review]
Thumps up @ClosedSourcerer

**Comment by nhaenis** [comment]
Updated links from `https://catena-x.net/de/standard-library` to `https://catenax-ev.github.io/docs/next/standards/CX-0128-DemandandCapacityManagementDataExchange` see <https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/955>

**Comment by ClosedSourcerer** [comment]
@evegufy 
image

https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-00/#keep-the-following-updated-for-each-pull-request-to-the-default-branch-main

This is technically no CodeContribution, but just KIT as Documentation. Hence I assume that the 1000 line rules does not apply here.

**Comment by AngelikaWittek** [comment]
@ClosedSourcerer 
> This is technically no CodeContribution, but just KIT as Documentation. Hence I assume that the 1000 line rule does not apply here.

The rule applies, please see: https://www.eclipse.org/projects/handbook/#ip-project-content
_"The content contains more than 1,000 lines of content (including documentation, code, configuration files, and other forms of source code)."_

**Comment by carslen** [comment]
> 
> The following issues are addressed.
> 
> [...]
> 
> https://github.com/catenax-eV/cx-ex-dcm/issues/14 
> https://github.com/catenax-eV/cx-ex-dcm/issues/21 
> https://github.com/catenax-eV/cx-ex-dcm/issues/12 
> https://github.com/catenax-eV/cx-ex-dcm/issues/7 
> https://github.com/catenax-eV/cx-ex-dcm/issues/10

To work open and transparent we shall not use/link to closed eco-systems in PRs in TractusX. I'm Committer of TractusX and unable to view these Issues thus I won't approve this PR.

**Comment by danielmiehle** [comment]
Just to sum it up:

- [ ] Please **resolve** the ECA conflicts. Fix e-mails in commit history / squash commits if necessary
- [ ] To ensure high-quality reviews, we would ask you to **divide** the PR into (reasonably) smaller PRs. This is good practice for both code and documentation reviews as described above.
- [ ] Please **execute** the IP check by the Eclipse Foundation for this PR.
- [ ] For the R24.08 KIT reviews, please add @jSchuetz88, as well as @maximilianong and me as reviewing committers (in addition to your business reviewers).
- [ ] For future KIT reviews, you will need dedicated reviewing committers for your KIT. @jSchuetz88 @stephanbcbauer: Can you please add this information in the upcoming townhall meetings.

Thank you for your support and for adapting the open topics!

**Comment by ClosedSourcerer** [comment]
There will be new PRs.

**Pull request closed without merging**
