### PR TITLE
Update TRG 4.07 - Read-only filesystems (old draft version)

### PR DESCRIPTION
**Pull request by Siegfriedk**
Please be aware: This TRG 4.07 is in draft for a long time and was not updated.

This PR is here to clarify with the community IF we delete the TRG 4.7 draft OR finish it.

### CODE REVIEW

**Comment by Siegfriedk** [comment]
> Like already mentioned in the [original PR](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/414#issuecomment-1750502480), integrating in TRG 4.03 would make sense

Not sure tbh. I think the topic is unique enough as it describes how to handle file permissions.

**Comment by florianrusch-zf** [comment]
For me personally, it doesn't matter whether we merge it with TRG 4.03 or not. However, I vote in favour of keeping this topic in principle and not dropping it.

**Comment by evegufy** [comment]
Hi @Siegfriedk I'm not too attached to have it integrated into TRG 4.03, it's also fine to have it merged as a separate TRG. @arnoweiss would that be also fine with you?

**Comment by arnoweiss** [comment]
Yes, I don't have very strong opinions on this either.

**Review by arnoweiss — APPROVED** [review]

**Review by evegufy — APPROVED** [review]

**Pull request merged**
