### PR TITLE
doc(conn): Fix two typos in connector kit

### PR DESCRIPTION
**Pull request by lgblaumeiser**
## Description

Reading through the connector kit I found two typos which I fixed with this pull request

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by arnoweiss** [comment]
Can you redirect this PR to here [1]? Then we'll avoid merge conflicts on main.

**Comment by lgblaumeiser** [comment]
Hi @arnoweiss , what exactly are you referring to? You refer to a footnote, which is not resolved.

**Comment by lgblaumeiser** [comment]
Hi @arnoweiss, tried that, issue is, that your branch is quite old and this adds 108 commits to my commit. I do not see a merge conflict, as your changes in the files I have adapted are in different places and git should be able to merge that without a conflict.

**Comment by lgblaumeiser** [comment]
@stephanbcbauer, can you advice me, whether I need to do something to get a review? And a hint, what I can do, to get also the failing check to a success. Thanks!

**Comment by arnoweiss** [comment]
The check is failing because the `DEPENDENCIES` file isn't updated properly. It's an eclipse foundation requirement. To solve:
1. Download Eclipse dash jar from [here](https://repo.eclipse.org/content/repositories/dash-licenses/org/eclipse/dash/org.eclipse.dash.licenses/1.1.0/).
2. Execute with adjusted paths (depending on where you downloaded the jar to and where package-lock.json and the DEPENDENCIES file are (project root).
```sh
java -jar ./org.eclipse.dash.licenses-1.1.0.jar package-lock.json -project automotive.tractusx -includeScope=test -summary ./DEPENDENCIES
```
3. commit the changes and push.
4. Pray to heaven that the pipeline passes (I've witnessed some entirely nondeterministic behavior when working on eclipse-edc)

**Comment by lgblaumeiser** [comment]
Dash tooling runs through locally without an issue, error message of check shows a return value 429 indicating too many requests, so I assume, that the check is not broken. Cannot restart the check, though.

**Review by maximilianong — APPROVED** [review]
Thanks for correcting the typos :)

**Review by stephanbcbauer — APPROVED** [review]
LGTM

**Comment by lgblaumeiser** [comment]
@stephanbcbauer @maximilianong Thanks for the reviews!

Would you be so kind and merge the PR?

**Pull request merged**
