### PR TITLE
bugfix: version update

### PR DESCRIPTION
**Pull request by manojava-gk**
change the version of dcm from 3.1.0 to 0.1.0 in changelog page

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM

**Comment by SebastianBezold** [comment]
Hi @manojava-gk,

AFAIK, the CHANGELOG is pulled in via remote-content-plugin. At least it is configured there. 
Is this a manual change, or is this done via build? Is this a change, that is also done in the the "true" CHANGELOG in [eclipse-tractusx/tractus-x-release](https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md).

Would be nice, if you can provide this as information when creating the PR

**Comment by maximilianong** [comment]
> Hi @manojava-gk,
> 
> AFAIK, the CHANGELOG is pulled in via remote-content-plugin. At least it is configured there. Is this a manual change, or is this done via build? Is this a change, that is also done in the the "true" CHANGELOG in [eclipse-tractusx/tractus-x-release](https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md).
> 
> Would be nice, if you can provide this as information when creating the PR

Hi @SebastianBezold its a manual change - I don't know where this information came from. Here is the truth on KIT level with 0.1.0 (https://eclipse-tractusx.github.io/docs-kits/kits/DCM%20Kit/changelog). 

@manojava-gk can you please change it in the true changelog aswell (https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md).

**Comment by SebastianBezold** [comment]
Hi @maximilianong,

I won't change this without any notice. The `CHANGELOG.md` was prepared by release management (@RolaH1t) together with @Siegfriedk. If there has been miscommunication, please clarify it together.

This whole issue raises the question, why we keep two versions of the `CHANGELOG` and even have different info in it. 
I would highly appreciate, if we can get rid of the `CHANGELOG.md` file in this repository and only link to the original source. This will prevent us from publishing wrong information

**Comment by maximilianong** [comment]
Hi @SebastianBezold - we did this as a quick fix, because in general it's already too late. I think we (Mano & me) should not take over the responsibility of information in a different repository. I think we can close this PR here then and wait for the official fix.

**Comment by SebastianBezold** [comment]
@maximilianong, but you have to address it, if it was a mistake. I think i'm going to remove the `CHANGELOG.md` in this repo here and provide a link to a the original source on a better suited page. 
Will keep you posted in this PR here, once I've prepared a suggestion.

For now, I think keeping the files in sync is better than to have them containing different info

**Comment by Siegfriedk** [comment]
@maximilianong the whole path is wrong btw. : https://eclipse-tractusx.github.io/docs-kits/kits/DCM%20Kit/changelog looks right while yours references 3.1.0

**Pull request closed without merging**
