### PR TITLE
Pull Request for ESS-kit updates for review from PR#814

### PR DESCRIPTION
**Pull request by birgitZF**
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by birgitZF** [comment]
I have no editing rights to resolve the conflicts: the changes I did earlier on Web-git are not included in my PR from my fork, that means these changes are not in my PR
docs-kits/kits/ESS-Kit/changelog.md --> replace page_adoption_view with Adoption View
docs-kits/kits/ESS-Kit/page_documentation.md --> correct you tube to youtube, resp. to respectively
docs-kits/kits/ESS-Kit/page_adoption-view.md  --> added links to industry kit and to Business Partner kit

**Comment by danielmiehle** [comment]
Hi @birgitZF, thanks for the update!

The change request of the static folder to the assets folder is not urgent. However, can you please fix the merge conflicts so that we can merge tmw.

image

fyi @maximilianong @HFocken @jSchuetz88

**Comment by birgitZF** [comment]
@danielmiehle can you please call me or send an invitation? I cannot resolve the conflicts, I do not know how. If I click on "resolve conflict", I can edit the file and correct it but I cannot save it!! Please advise.

**Review by jSchuetz88 — COMMENTED** [review]
As all of the chnages have bin included in the original pull request, this one can be deleted.

**Comment by birgitZF** [comment]
I will close this Pull Request as all changes are now covered in PR #814

**Pull request closed without merging**
