### PR TITLE
chore(ecopass-kit): added dpp-tutorial  & dpp-verification to the KIT adoption view

### PR DESCRIPTION
**Pull request by matbmoser**
## Description
There was missing the DPP Tutorial to be linked to the KIT. It was presented in the Second Tractus-X Community Days and it is really valuable for easing the adoption of the KIT.

I also added the dpp-verification documentation so that people can easily read more about the concept in the Digital Product Pass Verification Add-on Section.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by danielmiehle — APPROVED** [review]
LGTM

**Comment by matbmoser** [comment]
Sorry @danielmiehle and @catroest but I need your approval again...

**Review by catroest — APPROVED** [review]
LGTM

**Review by stanfaldin — CHANGES_REQUESTED** [review]
LGTM but since the content was changed an adaptation of the change log might be needed

**Review by danielmiehle — APPROVED** [review]

**Comment by matbmoser** [comment]
> LGTM but since the content was changed an adaptation of the change log might be needed

Ok i will also add the change log

**Review by saudkhan116 — APPROVED** [review]
Looks fine for me

**Pull request merged**
