### PR TITLE
documentation(kit-artifacts):broken link has been fixed

### PR DESCRIPTION
**Pull request by Unsharm**
## Description
In this pull request , we have fixed the broken link in kit artifacts file.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by SujitMBRDI** [comment]
Please fix dependencies file by either rebasing on main or using the dash licences tool,

- https://repo.eclipse.org/content/repositories/dash-licenses/org/eclipse/dash/org.eclipse.dash.licenses/
- [Eclipse Dash License Tool and Package Lock Files | Wayne Beaton](https://blog.waynebeaton.ca/posts/ip/dash-license-tool-package-lock/)

**Comment by Unsharm** [comment]
> Please fix dependencies file by either rebasing on main or using the dash licences tool,
> 
> * https://repo.eclipse.org/content/repositories/dash-licenses/org/eclipse/dash/org.eclipse.dash.licenses/
> * [Eclipse Dash License Tool and Package Lock Files | Wayne Beaton](https://blog.waynebeaton.ca/posts/ip/dash-license-tool-package-lock/)

Hi @SujitMBRDI, Okay

**Comment by arnoweiss** [comment]
There's a [new section on the readme](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io?tab=readme-ov-file#3rd-party-dependency-checks) that leads you through the process

**Comment by Unsharm** [comment]
> There's a [new section on the readme](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io?tab=readme-ov-file#3rd-party-dependency-checks) that leads you through the process

Hi @arnoweiss, Thank you I will follow the same steps.

**Review by SujitMBRDI — APPROVED** [review]
LGTM

**Review by arnoweiss — APPROVED** [review]

**Pull request merged**
