### PR TITLE
EcoPass KIT 24.08 adoption view adapted

### PR DESCRIPTION
**Pull request by catroest**
## Description
Please describe your PR: 
- new version numbers of models
- passage added to highlight which shared models are used

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by matbmoser — APPROVED** [review]
For me is fine, the latest models are public already we don't need an IP clearance here I believe

**Comment by matbmoser** [comment]
@catroest please check the identation

**Review by matbmoser — CHANGES_REQUESTED** [review]
Identention

**Review by LuisRickert — APPROVED** [review]

**Review by matbmoser — DISMISSED** [review]

**Comment by matbmoser** [comment]
I needed to update some things that were incorrect from the development view. All the things mentioned and added are already open source so no IP check is needed

**Review by matbmoser — DISMISSED** [review]

**Review by matbmoser — APPROVED** [review]

**Review by saudkhan116 — APPROVED** [review]

**Pull request merged**
