### PR TITLE
Chore/office hour 20240119

### PR DESCRIPTION
**Pull request by hzierer**
This PR adds the office hour meeting minutes to its new home on the Tractus-X page.

### CODE REVIEW

**Review by FaGru3n — CHANGES_REQUESTED** [review]
IMHO we should remove the recording section.

Rest looks fine for me.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Comment by FaGru3n** [comment]
Hi @stephanbcbauer, you maybe want to also review or share some input...

**Comment by stephanbcbauer** [comment]
> Hi @stephanbcbauer, you maybe want to also review or share some input... 

Thank you :) can we wait with merging until the office hour today? Thx

**Comment by FaGru3n** [comment]
> > Hi @stephanbcbauer, you maybe want to also review or share some input...
> 
> Thank you :) can we wait with merging until the office hour today? Thx

Sure unless we have 2 approvals we can not merge, but yeah we can wait.

**Review by SebastianBezold — APPROVED** [review]

**Comment by stephanbcbauer** [comment]
> > > Hi @stephanbcbauer, you maybe want to also review or share some input...
> > 
> > 
> > Thank you :) can we wait with merging until the office hour today? Thx
> 
> Sure unless we have 2 approvals we can not merge, but yeah we can wait.

Ah, sorry :). I was only on my cell phone before and thought it was about the open meeting. So the date itself and the ICS file and the session link :) with this PR there is need to wait :)

**Review by stephanbcbauer — APPROVED** [review]
LGTM

**Pull request merged**
