### PR TITLE
Add R24-05 Release-Notes, remove remainders of R23-09

### PR DESCRIPTION
**Pull request by arnoweiss**
## Description

Currently the changelog returns a 404 - it was likely accidentally removed previously. This PR restores it and adds the Releasenotes for R24-05.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by arnoweiss** [comment]
The snapshot was already introduced by https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/904.

**Comment by evegufy** [comment]
Was remove with https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/886

**Review by evegufy — APPROVED** [review]
Approved for changelog re-adding

@arnoweiss  not sure about the removal of `docs-kits_versioned_docs/version-23.09/kits/Digital Twin Kit/Software Development View/API EDC Discovery/post-list-of-bpns-to-retrieve-available-company-connector.api.mdx` who can confirm that and could you please add a hint about that in the PR title and description?

**Review by danielmiehle — APPROVED** [review]

**Review by tom-rm-meyer-ISST — APPROVED** [review]
Same as mentioned by @evegufy. @arnoweiss, what's the issue with the single open api file?

**Comment by arnoweiss** [comment]
The single file is currently the only file that is left of R23-09 [1]. It was removed with the removal of R23-09 [2] but reintroduced by a PR for R24-05 [3]. R23-09 isn't loaded by docusaurus anymore [4] so the file is just dangling.

[1] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/docs-kits_versioned_docs/version-23.09
[2] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/840
[3] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/850
[4] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/docs-kits_versions.json

**Comment by tom-rm-meyer-ISST** [comment]
> The single file is currently the only file that is left of R23-09 [1]. It was removed with the removal of R23-09 [2] but reintroduced by a PR for R24-05 [3]. R23-09 isn't loaded by docusaurus anymore [4] so the file is just dangling.
> 
> [1] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/docs-kits_versioned_docs/version-23.09 [2] #840 [3] #850 [4] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/main/docs-kits_versions.json

Ok thanks for claryfying. Already gave the approval. Now my go is "perfect".

**Pull request merged**
