### PR TITLE
docs: Knowledge Agents for CX 24.08 

### PR DESCRIPTION
**Pull request by drcgjung**
## Description

Updates Knowledge Agents Kit to the CX 24.08 Release.
Especially cares about including the AAS Bridge Release.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by arnoweiss — APPROVED** [review]

**Review by bosserf — APPROVED** [review]
Thanks Schorsch. Great Job!

**Review by obalandi — APPROVED** [review]

**Review by TomBuchertTSystems — APPROVED** [review]

**Review by matbmoser — APPROVED** [review]

**Comment by jSchuetz88** [comment]
@matbmoser @arnoweiss @stephanbcbauer @danielmiehle @maximilianong 
Could someone merge?

**Comment by drcgjung** [comment]
@maximilianong this hasnt been merged (and the changes are therefor also not in the "version" copy, I guess).
Could you please do that such that kit and repo documentation are in sync?

**Comment by stephanbcbauer** [comment]
@arnoweiss, @matbmoser is the IP Ticket missing? Cause of the amount of the changes? Is this the reason it was not merged?

**Comment by stephanbcbauer** [comment]
> @arnoweiss, @matbmoser is the IP Ticket missing? Cause of the amount of the changes? Is this the reason it was not merged?

created the [IP Ticket ](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16143)

**Pull request merged**
