### PR TITLE
bugfix: change community gallery faq target

### PR DESCRIPTION
**Pull request by manojava-gk**
change faq link in community gallery to Developer FAQ

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by SebastianBezold — CHANGES_REQUESTED** [review]
When you are already on it, please change the title. 
We do have 3 or more FAQ pages on our website. So what does this link actually forward to?

Also for future PRs, please provide more descriptive titles

**Review by maximilianong — APPROVED** [review]

**Comment by maximilianong** [comment]
@SebastianBezold your change request is blocking this at the moment. Can we agree on the issue I created. We will take this topic but not today.

**Comment by SebastianBezold** [comment]
@maximilianong, 

changing the title is a matter of seconds, so i think we should amend that. 
My suggestion would be "Developer FAQ".

Just switching from left to right without a proper title is not worth merging in my opinion

**Pull request closed without merging**
