### PR TITLE
chore(trg5.09): update workflow example to always use latest stable version of helm

### PR DESCRIPTION
**Pull request by hzierer**
## Description 
This PR removes the explicit definition of the to be installed helm version by the setup-helm action: Since the Action installs the latest stable version of helm by default anyways.

### CODE REVIEW

**Review by FaGru3n — DISMISSED** [review]
LGTM

**Review by FaGru3n — CHANGES_REQUESTED** [review]
LGTM maybe you can comment the helm version out, and add a description how you can use the step or workflow in your need to dedicated helm versions.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Comment by hzierer** [comment]
> LGTM maybe you can comment the helm version out, and add a description how you can use the step or workflow in your need to dedicated helm versions.

I left it on latest but added the option to workflow_dispatch to adjust the version

**Pull request merged**
