### PR TITLE
feat: enable markdown linter for kits

### LINKED ISSUE #673: Improve Markdown Quality by Enabling the Linter
### Description 
**As** a specification export of the KIT,
**I want** have a clean build,
**so that** there are no errors or warnings related to markdown issue.

This problem of bad-formated markdown files with broken links is often discussed. To solve this issue, the Markdown linter should be enforced in the `docs-kits` folder to prevent such issues during pull request reviews via GitHub action checks.

### Acceptance Criteria

- [x] Linter works in the `docs-kits` folder

### Additional Information
Example and related discussions: #639
Discussed the necessity of it with @danielmiehle, @arnoweiss, and @SebastianBezold.

### PR DESCRIPTION
**Pull request by mhellmeier**
## Description
This PR enables the markdown linter for the KITs.

Fixes #673 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by SebastianBezold — APPROVED** [review]
👍 I think it is the best option to merge it, even with failing check. These issues did pile up due to the lack of linting and should now be worked on collectively.

Separate issues per KIT would be fine in my opinion.

**Review by danielmiehle — APPROVED** [review]

**Comment by maximilianong** [comment]
Looks like all open PRs are now failing due to this new rule. How to handle this?

**Comment by arnoweiss** [comment]
I don't have fundamental problems with merging despite a failed linter check. But there should be a requirement that every update to every kit fixes THEIR issues for ALL releases.

**Comment by mhellmeier** [comment]
> Looks like all open PRs are now failing due to this new rule. How to handle this? Should we inform now the responsible of every KIT to resolve their issues?

Exactly, @maximilianong! Every KIT has to fix its linting errors. @SebastianBezold and I are planning to create a GitHub Issue for every KIT. It is important that this will be checked during the Quality Gates.



> I don't have fundamental problems with merging despite a failed linter check. But there should be a requirement that every update to every kit fixes THEIR issues for ALL releases.

The first part is correct, @arnoweiss: While the KIT developers are fixing their linting problems, merging with a failed pipeline is okay. For the second part: Since the current pipeline only checks the `docs` and the `docs-kits` folder and not the `docs-kits_versioned_docs`, only the current and future KIT versions need to be corrected. Fixing the old archived versions would be great, but is still optional.

**Pull request merged**
