### PR TITLE
doc(blog): add new blog entry for catena-x release day

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR adds a new entry for our news blog [section](https://eclipse-tractusx.github.io/blog). The content itself was provided by ARENA2036. Also, the picture was provided by them.

After the merge, there will be short information about the event, which will look like 
image

The full content will look like this

image
image

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by maximilianong — CHANGES_REQUESTED** [review]
Content looks good but the cover image, especially the Catena-X logo on it looks unsharp. The quality of the image / graphic should be improved.

**Comment by stephanbcbauer** [comment]
[like]  Stephan Bauer reacted to your message:
________________________________

**Review by maximilianong — APPROVED** [review]
👍

**Comment by stephanbcbauer** [comment]
This PR can be closed because we do not distribute the information via the website. It was only distributed via the mailing list. Thx everybody for your contribution.

**Pull request closed without merging**
