### PR TITLE
feat: initial release for modular production kit

### PR DESCRIPTION
**Pull request by dominikoeh**
## Description

This Pull Request introduces the first version of the Modular Production Kit in the Resiliency Domain in anticipation of the 23.12 release. It includes the Changelog, Adoption and Software Development View as wells as a white paper.

The content of the pull request is created by the Modular Production Team @wehrstedt-jan 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

@maximilianong @danielmiehle @SebastianBezold

### CODE REVIEW

**Review by SebastianBezold — DISMISSED** [review]
Cannot say much about the content, but maybe some general questions:

- Is it possible to get SVG versions of the images provided? This would ensure, that we can maintain the images.
- Where does the `modular-production-onboarding.pdf` come from? Is there an editable "raw" form of it. This is also related to maintainability of the contents
- Is it commonly agreed in KITs, that directory names contain spaces? I see that quite often, but find it uncomfortable, especially when it comes to linking. If the directory structure is present in URLs and links, the spaces always have to be URL encoded to %20 and so on.

All in all the PR looks good to me, but the image and PDF topic should be address somehow (maybe afterwards). The spaces in directories topic is just food for thought 😁

**Comment by dominikoeh** [comment]
> Cannot say much about the content, but maybe some general questions:
> 
> * Is it possible to get SVG versions of the images provided? This would ensure, that we can maintain the images.
> * Where does the `modular-production-onboarding.pdf` come from? Is there an editable "raw" form of it. This is also related to maintainability of the contents
> * Is it commonly agreed in KITs, that directory names contain spaces? I see that quite often, but find it uncomfortable, especially when it comes to linking. If the directory structure is present in URLs and links, the spaces always have to be URL encoded to %20 and so on.
> 
> All in all the PR looks good to me, but the image and PDF topic should be address somehow (maybe afterwards). The spaces in directories topic is just food for thought 😁

1. will check for SVGs of the images
2. The *raw* version currently is a Word document
3. For the creation of the KIT I checked the repository and the wiki since the spaces looked strange at first; yet the wiki also has examples containing them https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/wiki/How-to-create-a-KIT-website%3F

**Comment by dominikoeh** [comment]
PNG files have been replaced with SVG files

**Comment by SebastianBezold** [comment]
> PNG files have been replaced with SVG files

Ok cool thank you. Looks good from my side. I'll add @danielmiehle and @maximilianong to the reviewers section.
In case you did not know yet @dominikoeh, you can ask for review, when you have "triage" privileges. You'll get these privileges, when you are added as "Project Contributor". This role can be granted to you by any committer and we also prepared an [issue template](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-add-project-contributor.md&title=New+Tractus-X+project+contributor) for it

**Review by danielmiehle — APPROVED** [review]
LGTM

**Comment by danielmiehle** [comment]
@maximilianong we should update the how to create a KIT page concerning the directory names and spaces.

**Pull request merged**
