### PR TITLE
[Traceability KIT 24.12] Special Characteristics

### PR DESCRIPTION
**Pull request by johannsvarela**
## Description
This PR updates the sections below with new content for special characteristics for the upcoming release 24.12. For detailed information regarding the changes made have a look at the updated [changelog](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1064/files#diff-0d2b8761706a881f09d6700d174e87bb7508f4d79d956fb127d4bad8f98f184c) file.

- Business View
- Development View

## Related Issues
Fixes https://github.com/eclipse-tractusx/sig-release/issues/818 / https://github.com/catenax-eV/sig-roadmap/issues/167

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@johannsvarela can you please solve the conflicts? @jSchuetz88 , @eckardg coouls you please check conten wize?

Friendly reminder:

- Initial PR at latest: 15. November
- Merged at latest: 29. November

**Comment by johannsvarela** [comment]
@jSchuetz88 this PR shouldn't be merged until the corresponding aspect model _SpecialCharacteristic.Measurement 1.0.0 ([#784](https://github.com/eclipse-tractusx/sldt-semantic-models/pull/784))_ is completed and published.

Since the aspect model is introduced and described in detail for this KIT, the content of this PR must be adapted after the aspect model was finished.

**Comment by ndr-brt** [comment]
@johannsvarela same as https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1028#issuecomment-2490294854

**Comment by eckardg** [comment]
LGTM

**Review by jSchuetz88 — CHANGES_REQUESTED** [review]
Hi @johannsvarela,

looks good. Only two remarks from my side:
- please add a note, that special characteristics are not standardized yet
- please check for the results property (see comment)

**Comment by stephanbcbauer** [comment]
Overall PR is release relevant -> model needs to be fixed @LuisRickert, please provide a HOTFIX.
Content checked by @ther3sa , @jSchuetz88 , @stephanbcbauer

**Review by stephanbcbauer — APPROVED** [review]
LGTM , see previous comment

**Pull request merged**
