### PR TITLE
docs(oss): Updated the process of creating/managing repositories

### PR DESCRIPTION
**Pull request by AngelikaWittek**
## Description

- Updated the process of creating/managing repositories
-  Updated related links
- Changed the order of the sidebar in the DevHub for the FAQ page

## Pre-review checks
no

### CODE REVIEW

**Comment by carslen** [comment]
Waiting to get #360 fixed. After this issue got fixed, you'll need to rebase your branch from main.

**Comment by carslen** [comment]
Please rebase your branch from main to get fixes in your branch/PR. After rebase you should be able to execute `npm run docusaurus start` sucessfully.

**Comment by AngelikaWittek** [comment]
Done. Tested locally.

**Review by carslen — APPROVED** [review]
Fixed a small typo (TractusX → Tractus-X), now LGMT.

**Pull request merged**
