### PR TITLE
docs: publish Dependabot TRG

### PR DESCRIPTION
**Pull request by tomaszbarwicki**
PR to publish Dependabot Tractus-X Release Guideline (TRG-2.06):

image

image

### CODE REVIEW

**Comment by RoKrish14** [comment]
There is an open PR #[60](https://github.com/eclipse-tractusx/sig-security/pull/60) related to dependabot.yml. The PR also addresses necessary description in the security_tooling.md file.
@tomaszbarwicki Please feel free to drop a review.

**Comment by FaGru3n** [comment]
Hi @tomaszbarwicki a bit unsure will this also create the new one into our default `docs/release` directory currently GitHub shows me only the deletion of the file and not the move into different directory.

**Comment by tomaszbarwicki** [comment]
> Hi @tomaszbarwicki a bit unsure will this also create the new one into our default `docs/release` directory currently GitHub shows me only the deletion of the file and not the move into different directory.

@FaGru3n well spotted! fixed, thanks :)

**Review by RoKrish14 — CHANGES_REQUESTED** [review]
The entry of **dependabot.yml to trg-2-6 is not relevan**t. The updates related to deendabot are maintained under sig-security. Check [60](https://github.com/eclipse-tractusx/sig-security/pull/60).

**Comment by FaGru3n** [comment]
> The entry of **dependabot.yml to trg-2-6 is not relevan**t. The updates related to deendabot are maintained under sig-security. Check [60](https://github.com/eclipse-tractusx/sig-security/pull/60).

Hi @RoKrish14 guess then we will need a separate TRG for Dependabot (how use it / and have it present for the release) here on our webpage that could link to your files within sig-security, but we have to make it clear that security is part of our TRG´s, but the hard requirements depend on your work.

So guess @tomaszbarwicki wants to create this TRG and if you also want to spread the word for security tools maybe we can discuss the place like moving dependapot to the Security related TRG´s under the umcomming point 8.

What do you think about that @tomaszbarwicki @RoKrish14 ?

**Comment by RoKrish14** [comment]
I agree to the need of "moving dependapot to the Security related TRG´s under the upcomming point 8" and @klaudiaZF is in the process of creating the TRG 8.

**Comment by tomaszbarwicki** [comment]
Hi @RoKrish14, I'm open to move it to security section when it gets created. Shall we pause the PR or park it temporarily in the GIT section?

**Comment by RoKrish14** [comment]
@tomaszbarwicki : @klaudiaZF told me that your PR will go through with necessary changes. Once approved, it could be moved to TRG 8.0. 
So, I would say, lets do that, lets focus on this PR about dependabot (Y). Later we can move it to TRG 8

**Review by FaGru3n — DISMISSED** [review]
LGTM

**Review by klaudiaZF — COMMENTED** [review]
Can you add npm and Gradle to yaml file and add information that open pull requests limits and interval can be set up based on team needs?

**Comment by RoKrish14** [comment]
> Can you add npm and Gradle to yaml file and add information that open pull requests limits and interval can be set up based on team needs?

This wont be necessary.
There are other [options](https://docs.github.com/de/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) too that can be enabled based on use case.

**Comment by tomaszbarwicki** [comment]
@klaudiaZF , @RoKrish14 incorporated your suggestions to add more dependabot config sample description informing about ability to customize certain parameters, included as well the link pointing to available ecosystem packages. Does that address your view? -> https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/659/commits/666c60cbf91f4a381ddca9e892e63f6885d65786

**Comment by RoKrish14** [comment]
> @klaudiaZF , @RoKrish14 incorporated your suggestions to add more dependabot config sample description informing about ability to customize certain parameters, included as well the link pointing to available ecosystem packages. Does that address your view? -> [666c60c](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/commit/666c60cbf91f4a381ddca9e892e63f6885d65786)

Yes, thanks a lot.

**Review by RoKrish14 — APPROVED** [review]
Looks complete to me 👍

**Review by klaudiaZF — APPROVED** [review]

**Review by SebastianBezold — APPROVED** [review]

**Review by FaGru3n — APPROVED** [review]
LGTM

**Pull request merged**
