### PR TITLE
doc(tutorials): publish the e2e adopter journey tutorial

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR is the final step to merge the feature branch to main and publish the e2e adopter journey tutorial.

- The main parts are the [tutorial section](https://stephanbcbauer.github.io/eclipse-tractusx.github.io/docs/tutorials) itself
- The [first](https://stephanbcbauer.github.io/eclipse-tractusx.github.io/docs/tutorials/e2e/) tutorial
- The [blog entry](https://stephanbcbauer.github.io/eclipse-tractusx.github.io/blog/release-tutorials)

> note: Please be aware, the links reference to a private fork which currently displays the changes of this PR.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by arnoweiss** [comment]
What's the tractusx-edc version used here? Some payloads look weird like
```json
{
    "querySpec": {
        "offset": 0,
        "limit": 100,
        "filter": "",
        "range": {
            "from": 0,
            "to": 100
        },
        "criterion": ""
    }
}
that looks way different than the[ openAPI definition](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0-SNAPSHOT#/QuerySpec).
```

**Comment by stephanbcbauer** [comment]
> What's the tractusx-edc version used here? Some payloads look weird like
> 
> ```json
> {
>     "querySpec": {
>         "offset": 0,
>         "limit": 100,
>         "filter": "",
>         "range": {
>             "from": 0,
>             "to": 100
>         },
>         "criterion": ""
>     }
> }
> ```
> 
> that looks way different than the[ openAPI definition](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0-SNAPSHOT#/QuerySpec).

Its 0.5.1 the one which is also mentioned in the related standards

**Comment by arnoweiss** [comment]
What is `filter` supposed to mean?
What is `criterion` supposed to mean?
What is `range` supposed to mean?

None of these properties for a `QuerySpec` are mentioned in the openAPI spec for tractusx-edc 0.5.1.

**Comment by stephanbcbauer** [comment]
> What is `filter` supposed to mean? What is `criterion` supposed to mean? What is `range` supposed to mean?
> 
> None of these properties for a `QuerySpec` are mentioned in the openAPI spec for tractusx-edc 0.5.1.

@jkbquabeck , @MoritzDieckmann

**Comment by jkbquabeck** [comment]
I am not sure who worked on this. Maybe @alexandrudanciu @hemantxpatel or @paullatzelsperger know the answer here.

**Comment by hemantxpatel** [comment]
Hi, the correct `spec` will be:
```json
{
    "querySpec": {
        "offset": 0,
        "limit": 100
    }
}
```
I have referred the existing querySpec from some postman collections. Strangely it doesn't fail or warn, that's why it got skipped.
There are couple of usages in mxd as well. Will raise an issue and fix it.

**Comment by arnoweiss** [comment]
> Hi, the correct `spec` will be:
> 
> ```json
> {
>     "querySpec": {
>         "offset": 0,
>         "limit": 100
>     }
> }
> ```
> 
> I have referred the existing querySpec from some postman collections. Strangely it doesn't fail or warn, that's why it got skipped. There are couple of usages in mxd as well. Will raise an issue and fix it.

@hemantxpatel - Link the ticket here when it's created, please. I've observed the querySpec mechanism behaving strange in a couple of similar situations.

@stephanbcbauer - can you update the relevant parts in the tutorial? Ctl-F "querySpec" should show you all relevant occurences of the error above and I don't have push rights for this repo.

**Comment by hemantxpatel** [comment]
I raised issue here. eclipse-tractusx/tutorial-resources#166 

> I've observed the querySpec mechanism behaving strange in a couple of similar situations.

@arnoweiss Since these fields are unknown, they might get silently ignored during Json Serialization and should not affect any functionalities.

**Comment by arnoweiss** [comment]
Misunderstanding - sorry. I thought you'd open an issue about the EDC's behavior. I'll collect some more examples and then do it myself. Thanks for taking care of this and letting Stephan off my hook.

**Comment by stephanbcbauer** [comment]
> Misunderstanding - sorry. I thought you'd open an issue about the EDC's behavior. I'll collect some more examples and then do it myself. Thanks for taking care of this and letting Stephan off my hook.

To not confuse others, I will adapt the sections before we release the tutorial.

**Pull request merged**
