### PR TITLE
feat(tutorials): update feature branch tutorials

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR is just for updating the tutorials feature branch, cause it is really old. We still need this feature branch to work on the initial tutorial section.

No need for a review, cause the review is done, when the tutorial branch is merged to main. There are so many changes, cause the structure of tractusx.github.io has changed

### CODE REVIEW

**Review by carslen — COMMENTED** [review]
Hey @stephanbcbauer 
thanks for this PR. But to be honest, I have issues with this PR because it is way too big. A PR with 129k lines of changed code, over 650 commits - who shall review this in appropriate manner?

Due to our rules, we're required to open a IP check. But i expect Eclipse-Foundation IP-Check team to be really happy to review such a PR.

As an elected committer, you should have known that this PR was in violation of EF and TRG rules and that it might have been a good idea to split the PR into much smaller parts. I am really sorry to say it this way.

**Comment by carslen** [comment]
> No need for a review, cause the review is done, when the tutorial branch is merged to main. There are so many changes, cause the structure of tractusx.github.io has changed

As it is a external contribution we need a review here.

**Comment by danielmiehle** [comment]
@carslen : What do you mean with external contribution?

**Comment by FaGru3n** [comment]
Hi @stephanbcbauer as we already synced i would also decline this PR, because of the size an that we can not be sure if something will be missed if we merge it into main.

as already pointed out in our conversation, If such big PR come into our way we need to open a IP-Issue against the EF. see https://www.eclipse.org/projects/handbook/#ip-faq point 2.
image

So if there urgent things you will need to change on main i would please you to open a new PR from a different branch eg. `feat/new-feature` or in our case `doc/update-documentation`

**Comment by SebastianBezold** [comment]
Hey all, since the PR does not target main, but a feature branch, I can see why it is so big. 
It just takes the whole history from main. So content, that has already gone through regular PRs.

@stephanbcbauer can you confirm that?

**Comment by stephanbcbauer** [comment]
> Hey all, since the PR does not target main, but a feature branch, I can see why it is so big. It just takes the whole history from main. So content, that has already gone through regular PRs.
> 
> @stephanbcbauer can you confirm that?

yes can confirm this :) the initial feature branch was created month ago :) and unfortunatly was never rebased :( and yes the changes were already reviewed :)

But to provide better feelings... i created a new feature branch and published the intial changes (created by felix gerbig) -> this is our base to work on the tutorial.

**Comment by stephanbcbauer** [comment]
> > @carslen : What do you mean with external contribution?
> 
> The PR is initiated from a fork of this repository.

@carslen i am confused :) cause all teams work with forks and provide changes to origin with a PR from fork -> origin. Whats wrong here? Did i missunderstand something?

**Pull request closed without merging**
