### PR TITLE
Chore-publish-SEC-TRGs

### PR DESCRIPTION
**Pull request by kelaja**
SEC TRGs have been in DRAFT for two weeks, so I propose to publish them now.

### CODE REVIEW

**Review by RolaH1t — APPROVED** [review]

**Comment by RolaH1t** [comment]
Happy to fully enable those TRGs and apply them for all inputs to R24.05

**Comment by FaGru3n** [comment]
Hi @kelaja,

you should provide this information that the security trg´s will "go live" with this pr so every member of Eclipse Tractus-X should be informed in my humble opinion. (Matrix Chat / Mailing List / Office Hour)

**Comment by klaudiaZF** [comment]
Hi @kelaja yes we can publish Security TRG, thank you for creating this PR. Can you just please fix numbering? Because right now we have TRG 8.01 and then TRG 8.03,TRG 8.04 and TRG 8.05. We wasn't sure what to do with SNYK and since we decided to keep SNYK out of TRGs, we have a numbering gap. 

Thank you in advance

**Review by klaudiaZF — CHANGES_REQUESTED** [review]
Change TRG 8.03 to TRG 8.02
Change TRG 8.04 to TRG 8.03
Change TRG 8.05 to TRG 8.04

**Comment by RolaH1t** [comment]
> Change TRG 8.03 to TRG 8.02 Change TRG 8.04 to TRG 8.03 Change TRG 8.05 to TRG 8.04

ok for me

**Review by klaudiaZF — APPROVED** [review]

**Comment by kelaja** [comment]
@klaudiaZF @RolaH1t @RoKrish14 kindly see the requested changes applied. The TRGs are ready for being published now.

**Comment by klaudiaZF** [comment]
@kelaja approved, thank you

**Review by RoKrish14 — APPROVED** [review]
LGTM 👍

**Comment by kelaja** [comment]
@FaGru3n there seems to be a check that fails, kindly guide how can we do the merge?

**Comment by FaGru3n** [comment]
> @FaGru3n there seems to be a check that fails, kindly guide how can we do the merge?

There is an open IPLab issue for 3rd party check:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13991

so have to wait for Eclipse IP Team to validate the check and also some other PR´s have to wait for the dependency check...

**Review by RolaH1t — APPROVED** [review]
Ok to publish

**Review by Siegfriedk — APPROVED** [review]

**Comment by klaudiaZF** [comment]
Hi @kelaja I've just notice that the name of the folder is just "trg-8" therefore it looks bad on site. Is there a way to change it for "TRG 8 - Security" ?

**Comment by Siegfriedk** [comment]
> Hi @kelaja I've just notice that the name of the folder is just "trg-8" therefore it looks bad on site. Is there a way to change it for "TRG 8 - Security" ?

I fixed it in another PR

**Pull request merged**
