### PR TITLE
docs(certificate-management-kit):icon format changed to SVG

### PR DESCRIPTION
**Pull request by Unsharm**
## Description
In this pull request, I have changed the format of icon's image in architecture view, software deployment view  of the Certificate management  kit from .PNG to .SVG.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by SujitMBRDI — CHANGES_REQUESTED** [review]
@Unsharm, Kindly make changes to Adaption view, changelog and for operartion view pages as well. As these pages also containing broken svg image.

**Comment by Unsharm** [comment]
> @Unsharm, Kindly make changes to Adaption view, changelog and for operartion view pages as well. As these pages also containing broken svg image.

@SujitMBRDI okay, i am making the changes.

**Comment by Unsharm** [comment]
> > @Unsharm, Kindly make changes to Adaption view, changelog and for operartion view pages as well. As these pages also containing broken svg image.
> 
> @SujitMBRDI I have updated the icon image from previous image to the new one as requested, but I have already changed the format of the icon's image in adoption view, changelog, and operations view and these changes have already been merged. It should be work.

**Review by SujitMBRDI — APPROVED** [review]

**Comment by SebastianBezold** [comment]
Hi @Unsharm,

are the `.png` versions of the images still in use somewhere? If so, consider replacing this usage by the `.svg` file as well an delete the `.png` files afterwards, if they are no longer used

**Comment by Unsharm** [comment]
> Hi @Unsharm,
> 
> are the `.png` versions of the images still in use somewhere? If so, consider replacing this usage by the `.svg` file as well an delete the `.png` files afterwards, if they are no longer used

Hi @SebastianBezold,I have updated all the kits' icons from PNG TO SVG format. This changes will be implemented in the Next version. I will double-check to ensure no kits' icons are left in PNG format.

**Comment by Unsharm** [comment]
> > > Hi @Unsharm,
> > > are the `.png` versions of the images still in use somewhere? If so, consider replacing this usage by the `.svg` file as well an delete the `.png` files afterwards, if they are no longer used
> > 
> > 
> > Hi @SebastianBezold,I have updated all the kits' icons from PNG TO SVG format. This changes will be implemented in the Next version. I will double-check to ensure no kits' icons are left in PNG format.
> 
> Hi @Unsharm,
> 
> I'm not sure, if I understand you correctly. Will you remove the `.png` files? If so, I would prefer to have it in this PR and not an additional one

>Hi @SebastianBezold 
>I wanted to inform you that i have created a separate folder named "kit-icons" where all images are now in SVG format. please note that i am not deleting any existing PNG images. This change will only apply to the next version.

**Comment by SebastianBezold** [comment]
Hi @Unsharm,
Ok understood. My point was, that you actually __should__ delete the .png files if they are not used anymore. No need to keep them around in this case

**Comment by Unsharm** [comment]
> Hi @Unsharm, Ok understood. My point was, that you actually **should** delete the .png files if they are not used anymore. No need to keep them around in this case

>Hi @SebastianBezold Yes, we kept the .png files that are in use.

**Review by maximilianong — APPROVED** [review]

**Comment by maximilianong** [comment]
> Hi @Unsharm, Ok understood. My point was, that you actually **should** delete the .png files if they are not used anymore. No need to keep them around in this case

Jup - that's our next step. Cleaning ..

**Pull request merged**
