### PR TITLE
chore(ecopass): fixed broken images bug in images svgs in compilation

### LINKED ISSUE #930: [Eco Pass] warning for broken images
### Current Behavior
The build issues warnings that it can't process SVGs from the Eco Pass Kit. The image does however appear to render correctly. The same issue occurs for other kits, so a fix could be rolled out elsewhere too.

```
[WARNING] The image at "/mnt/c/Users/usr/IdeaProjects/eclipse-tractusx.github.io/docs-kits_versioned_docs/version-24.03/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /mnt/c/Users/usr/IdeaProjects/eclipse-tractusx.github.io/docs-kits_versioned_docs/version-24.03/kits/Eco_Pass_KIT/resources/adoption-view/adoption-view-ValueChainBenefits.svg)
[WARNING] The image at "/mnt/c/Users/usr/IdeaProjects/eclipse-tractusx.github.io/docs-kits_versioned_docs/version-24.03/kits/Eco_Pass_KIT/resources/development-view/dataRetrievalFlow.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /mnt/c/Users/usr/IdeaProjects/eclipse-tractusx.github.io/docs-kits_versioned_docs/version-24.03/kits/Eco_Pass_KIT/resources/development-view/dataRetrievalFlow.svg)
```

### Expected Behavior
No build warning.

### Steps To Reproduce
1. clone
2. npm install
3. npm start
4. behold logs

### PR DESCRIPTION
**Pull request by matbmoser**
## Description

There was a bug that was reported theissue below where broken images "svgs" were not possible to be compiled.

closes #930 

### Issues Fixed
- Fixed dataRetrievalFlow image from Software View
- Fixed value chain benefits image from Adoption View

### Deleted
- Removed images that were not in use (Old Architecture Diagram)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by matbmoser** [comment]
I dont know why but since I have sanitized the SVG I can not edit it with draw.io

**Comment by matbmoser** [comment]
No dependency was added
just cloned from main

**Comment by matbmoser** [comment]
> I dont know why but since I have sanitized the SVG I can not edit it with draw.io

Ok this was fixed

**Comment by matbmoser** [comment]
Thank you @arnoweiss for the support in solving the Dependency problem. I was thinking that the dash dependencies were updated with the 3rd party dependency pipeline automatically.

**Review by arnoweiss — APPROVED** [review]
Build warnings are gone. There's a similar issue in the Modular Production Kit. Can you elaborate a bit on how you fixed this?

**Comment by matbmoser** [comment]
@arnoweiss there was a problem with the formating from the SVG files. I solved by recreating the images again in draw.io. Some of them probably is a export problem, people need to export the svgs correctly in Draw.io

**Review by maximilianong — APPROVED** [review]

**Pull request merged**
