### PR TITLE
Switched documentation from product-edc to tractusx-edc

### PR DESCRIPTION
**Pull request by stephanbcbauer**
Since [product-edc](https://github.com/catenax-ng/product-edc/tree/main) represents version 0.3.0 i switched to [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc) documentation which maps to 0.1.6

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@danielmiehle @stefan-ettl this change represents the current state of 0.1.6 and tractusx-edc. Right now we have product-edc online, which represents 0.3.0 ... to be in sync we should merge this PR. If there are some worries, please let me know.

**Comment by Siegfriedk** [comment]
Daniel is on holiday; There is one concern i have: We link this page now on the changelog to 3.0.1. you might want to add a 'moved' page on the old location.

**Comment by stephanbcbauer** [comment]
> Daniel is on holiday; There is one concern i have: We link this page now on the changelog to 3.0.1. you might want to add a 'moved' page on the old location.

Hey @Siegfriedk not sure about the 'moved' page. There is no change for the user. There is still the connector-Kit. Its just in a different structure, which represents the tractusx-edc structure and not the product_edc structure.

I will call you tomorrow for clarification.

thx

**Comment by stephanbcbauer** [comment]
Additional comment. @stefan-ettl the changes represent the tractusx-edc repository but the edc version 0.1.6. This is still correct? Just to be sure... the current eclipse-tractusx.github.io version is mapped to edc version 0.1.6?!?

**Comment by Siegfriedk** [comment]
@stephanbcbauer if you do this now, doesn't the URL from the kit page change? If yes, you should create a 'move' page as we reference that page on the Changelog.

I'm available though

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer if you do this now, doesn't the URL from the kit page change? If yes, you should create a 'move' page as we reference that page on the Changelog.
> 
> I'm available though

@Siegfriedk Ah sorry, now I get your point. Didn't know about the URL reference. Which URL is referenced? Can you link the changelog here, please?

I will create a short MD (generated as HTML) file which is shown when the referenced link in the changelog is clicked. There I will write a short sentence and link to the “new” Connector Kit in the new structure. 

THX

**Comment by Siegfriedk** [comment]
@stephanbcbauer its in our official eclipse tractus-x release: https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer its in our official eclipse tractus-x release: https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md

@Siegfriedk please let me know if I am wrong or maybe there is a misunderstanding, but the link in the release changelog points to https://eclipse-tractusx.github.io/docs/category/connector-kit/ which is fine… this is a generated link and this won't change even if I change the internal structure within this PR.

Only the Version 1.0.0 links to our changelog directly https://eclipse-tractusx.github.io/docs/kits/product-edc/CHANGELOG This file won't be there anymore after the restructuring. Therefore, I will adapt this file and add the information “Please be aware the pages has moved … and the link”

**Comment by Siegfriedk** [comment]
@stephanbcbauer the connector kit link to https://eclipse-tractusx.github.io/docs/kits/product-edc/CHANGELOG are we looking at the wrong thing? Should we have a short call?

**Comment by stephanbcbauer** [comment]
Will create a new PR after we finalized the documentation in our repository

**Pull request closed without merging**
