### PR TITLE
Fix Traceability Policy example

### PR DESCRIPTION
**Pull request by matgnt**
- Remove space before 'http' (linter?)
- Use 'Set' instead of 'Policy' because of EDC
- prefix UsagePurpose with according value namespace cx.core.*
- Remove version from cx-policy namespace
- Update FrameworkAgreement rightOperand with upper case credential name

### CODE REVIEW

**Comment by matgnt** [comment]
@arnoweiss could you also review the changes, please. Thanks,
Matthias

**Review by mhellmeier — CHANGES_REQUESTED** [review]
Policies look good so far.

Please check if the changelog needs to be updated.

Please update the `DEPENDENCIES` file (have a look at the failed pipeline). Otherwise, merging isn't possible.

**Comment by arnoweiss** [comment]
This might create conflicts with #792 so it might make sense to redirect the PR there?

**Comment by matgnt** [comment]
@mhellmeier Changelog added and DEPENDENCIES updated.

**Review by mhellmeier — APPROVED** [review]

**Review by tom-rm-meyer-ISST — APPROVED** [review]
LGTM, verified locally that the contract policy (at least Trace credential) is successfully validated during negotiation.

**Pull request merged**
