### PR TITLE
fix: Removal of duplicates in the Upcoming KITs

### PR DESCRIPTION
**Pull request by jSchuetz88**
This PR:

removes the duplicates from the "Upcoming KITs" that resulted from the merged R24.05 PRs.
corrects wrong version in changelogs (Quality and Data Chain).

### CODE REVIEW

**Review by maximilianong — APPROVED** [review]

**Comment by arnoweiss** [comment]
This is a great opportunity to conduct a live review of https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/911/files as it explains how to fix the pipeline build error you are encountering (tried again a second ago - clearlydefined is up again so pushing an empty commit will fix it).

**Comment by jSchuetz88** [comment]
> This is a great opportunity to conduct a live review of https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/911/files as it explains how to fix the pipeline build error you are encountering (tried again a second ago - clearlydefined is up again so pushing an empty commit will fix it).

Seems to work like a charm

**Review by danielmiehle — APPROVED** [review]
LGTM - thanks for cleaning up @jSchuetz88 !

**Comment by danielmiehle** [comment]
@jSchuetz88 can you also remove the "upcoming KITs" section in the nav bar, please?

**Comment by arnoweiss** [comment]
would be happy to approve this if the nav bar is changed as Daniel suggested.

**Comment by danielmiehle** [comment]
@jSchuetz88 : any updates?

**Comment by jSchuetz88** [comment]
I think, we can close this PR, as there is an new PR (#927) which also closes this issue with a less intrusive change.

**Pull request closed without merging**
