### PR TITLE
Feat(Business Partner KIT): Release 2405

### PR DESCRIPTION
**Pull request by SujitMBRDI**
## Description

In this pull request, we have updated Business Partner KIT with new versioned apis for each service in BPDM.
Also, updated sidebar.js to adapt api controller structure accordingly.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by HFocken — APPROVED** [review]
Thank you - good to go!

**Review by maximilianong — APPROVED** [review]

**Review by danielmiehle — APPROVED** [review]
LGTM

**Comment by evegufy** [comment]
Hi @SujitMBRDI @danielmiehle @maximilianong with this pull request you accidentally remove the `src/pages/CHANGELOG.md`, re-adding it now with https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/909
image

**Comment by SujitMBRDI** [comment]
> Hi @SujitMBRDI @danielmiehle @maximilianong with this pull request you accidentally removed the `src/pages/CHANGELOG.md`, re-adding it now with #909 image

Hello @evegufy, sorry it was done accidentally.
But thanks for adapting changes.

**Pull request merged**
