### PR TITLE
docs(circularity-kit): add definition of Core to glossary

### PR DESCRIPTION
**Pull request by ybidois**
## Description

Add definition of Core to glossary as provided by @florianstern 

Fixes https://github.com/eclipse-tractusx/sig-release/issues/763

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by florianstern — APPROVED** [review]

**Comment by ybidois** [comment]
@danielmiehle @maximilianong @stephanbcbauer The website dependencies are very, very out of date, see screenshot. We cannot update them easily, because we need a strategy there:
- Do we want to upgrade to Docusaurus 3/3.5? https://docusaurus.io/docs/migration/v3
- Who will review the upgrade and changes to the UI?
Not sure who's responsible for this, but we better put it on the roadmap for 25.03! 
image

**Comment by stephanbcbauer** [comment]
> @danielmiehle @maximilianong @stephanbcbauer The website dependencies are very, very out of date, see screenshot. We cannot update them easily, because we need a strategy there:
> 
> * Do we want to upgrade to Docusaurus 3/3.5? https://docusaurus.io/docs/migration/v3
> * Who will review the upgrade and changes to the UI?
> 
> Not sure who's responsible for this, but we better put it on the roadmap for 25.03!
> 
> Happy to help, in any case.
> 
> image

@ybidois lets have a call :) Thx

**Comment by maximilianong** [comment]
We already tried / wanted to upgrade. Was not so easy.
@manojava-gk can you explain again what you can Sebastian already did and why it got stuck?

But in general, we should upgrade.
I think @manojava-gk can support here but someone from the association should take over the coordination :D

**Comment by ybidois** [comment]
> We already tried / wanted to upgrade. Was not so easy. @manojava-gk can you explain again what you and Sebastian already did and why it got stuck?
> 
> But in general, we should upgrade. I think @manojava-gk can support here but someone from the association should take over the coordination :D

I've discussed with @stephanbcbauer and we will tackle this together. He will take over the coordination and I will help him with the upgrade. Hopefully we can learn from everyone's attempts to do the merge and make it work! 😂

@maximilianong can you approve my PR? We got all checks green for now thanks to the help of Stephan.

**Review by maximilianong — APPROVED** [review]

**Review by SujitMBRDI — APPROVED** [review]

**Comment by ybidois** [comment]
@stephanbcbauer can you merge my PR please?

**Pull request merged**
