### PR TITLE
docs(open meetings): delete downloadable calendar files

### PR DESCRIPTION
**Pull request by stephanbcbauer**
## Description

This PR deletes the unused ics files (as in the office hour discussed):

- security-office-hour.ics
- coordination-feature-development-trace-x.ics
- alignment-and-planning-trace-x.ics

and it also deletes the broken files (daylight/summer/wintertime)

- committer-office-hour.ics
- office-hour.ics
- portal-open-meeting.ics

it also deletes the reference to these files in the open meetings.

- Only for the EDC weekly, i didn't delete it cause somehow it works here @lgblaumeiser -> please confirm
- also for the one-time meetings the files are not deleted, cause these files were created during coreect daylight/wintertime/summertime

**Please also help to discuss the schedules (e.g. schedule="Every Tuesday from 10:30 am to 11:00 am CEST") what would here the best? Since CEST doesn't fit any more.**

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
it appears that you remove much more ics file than meetingLinks

**Comment by stephanbcbauer** [comment]
> it appears that you remove much more ics file than meetingLinks

yes you are right -> cleanup, cause for trace-x we had two ics files, but the related open meetings were already deleted some time ago.

**Review by lgblaumeiser — CHANGES_REQUESTED** [review]
We should be consequent, there is the extended EDC meeting, where the calender file should be gone as well. And I would propose to also do this for the one time meetings. But I would agree to not change them, as the planning is just on Wednesday. We could remove them afterwards and change procedure for next time.

**Review by lgblaumeiser — APPROVED** [review]
LGTM

**Review by ClosedSourcerer — APPROVED** [review]
- 7 ICS files are to be removed
- 4 meetingLink= referencing ICS files are to be removed
- 4 meetingLink= and ICS files do remain
- The ICS files for Refinement Day 1 has an teams invite link set as location
image
 
The proposed changes LGTM, but imho all ICS files and references should be removed for consistency

**Comment by stephanbcbauer** [comment]
> approved with understanding that a change to improve consistency will follow after tomorrow's planning

Correct -> after tomorrow ... there will be a new PR deleting all the other calendar files.

**Pull request merged**
