### PR TITLE
doc(circularity kit): add informational requirements at end of life

### PR DESCRIPTION
**Pull request by stanfaldin**
## Description
this pull request adds the informational requirements for the end of live data parameters to enable remanufacturing and recycle use cases

Fixes https://github.com/eclipse-tractusx/sig-release/issues/632

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by jSchuetz88 — CHANGES_REQUESTED** [review]
Hi @stanfaldin,

sorry for the late review. Looks good to me, but one minor request. Please also update the "page_changelog.md" accordingly.

**Review by danielmiehle — DISMISSED** [review]
LGTM

**Review by matbmoser — DISMISSED** [review]
LGTM

**Comment by stanfaldin** [comment]
> Hi @stanfaldin,
> 
> sorry for the late review. Looks good to me, but one minor request. Please also update the "page_changelog.md" of the Circularity Kit accordingly. It should be version 1.2.0.

@jSchuetz88 change log adapted, please review again

**Review by danielmiehle — APPROVED** [review]
LGTM

**Review by matbmoser — APPROVED** [review]

**Comment by stanfaldin** [comment]
@matbmoser can you merge it ?

**Pull request merged**
