### PR TITLE
docs: delete unused content to avoid confusion

### PR DESCRIPTION
**Pull request by SebastianBezold**
## Description

This PR removes some files, that apparently where not used anywhere. They are not included in any menu and the lack of content also supports, that they might have been added at a very early stage but never got worked on.

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM maybe an screenshot or picture what you removed would help others to verify your changes.

**Comment by SebastianBezold** [comment]
> LGTM maybe an screenshot or picture what you removed would help others to verify your changes.

How would I add a screenshot of something that was never rendered on the website? 😁

**Comment by FaGru3n** [comment]
> > LGTM maybe an screenshot or picture what you removed would help others to verify your changes.
> 
> How would I add a screenshot of something that was never rendered on the website? 😁

kay this is the reason why i did not find any paricular. Thanks for the info 😉

**Review by hzierer — APPROVED** [review]
:+1:

**Review by carslen — APPROVED** [review]
Looks reasonable.

**Pull request merged**
