### PR TITLE
feat: added vault image to TRG 4.06

### PR DESCRIPTION
**Pull request by tom-rm-meyer-ISST**
## Description
The vault image with an image tag lower 1.14.2 are licensed unter MPL2.0 receives security updates by end of this year. For current use this is OK. See this [discussion](https://github.com/eclipse-tractusx/sig-infra/discussions/233).

This PR closes [sig-infra issue 247](https://github.com/eclipse-tractusx/sig-infra/issues/247).

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by tomaszbarwicki — CHANGES_REQUESTED** [review]
hi @tom-rm-meyer-ISST, thanks for creating PR with the vault image proposal. I suggest we first create a draft version with the change of new image so everyone interested can provide feedback before we publish it. Please follow described process: https://eclipse-tractusx.github.io/docs/release

**Comment by tom-rm-meyer-ISST** [comment]
I reverted the changes to TRG 4.06 and
- moved the changed file to folder trg-0
- added an entry to table trg-0/trg-0.md

Please check, if I got the process right. 

If yes, thenI can write to the mailing list. I guess it still is a fast release case, isn't it?

**Review by tomaszbarwicki — APPROVED** [review]
LGTM

**Comment by tom-rm-meyer-ISST** [comment]
@tomaszbarwicki shall I write the mail with regard to this PR or do we need to merge first so that I can review the draft on https://eclipse-tractusx.github.io/docs/release/trg-0/ ?

**Comment by tom-rm-meyer-ISST** [comment]
Hey @SebastianBezold, could you please check and merge so that we can ask the others via the mailing list?

**Comment by tom-rm-meyer-ISST** [comment]
Resolved merge conflict. After merging, I'll write to the mailing list. Last time @AngelikaWittek told us to keep holding as we're waiting for updates regarding the [licence issue](https://github.com/eclipse-tractusx/sig-infra/discussions/233).

**Comment by carslen** [comment]
Unfortunately there is another merge conflict after merging a different PR. Sorry.

**Comment by tom-rm-meyer-ISST** [comment]
> Unfortunately there is another merge conflict after merging a different PR. Sorry.

resolved

**Review by almadigabor — APPROVED** [review]
I've approved the changes and merged the PR. @tom-rm-meyer-ISST you can send the mail you discussed in the previous comments.

**Comment by almadigabor** [comment]
Hey @SebastianBezold! Good point, but it's still draft and up to changes so can be corrected if necessary. I only looked at the comments and was already approved and wasn't merged only because of merge conflicts.

**Pull request merged**
